### ISSUE TITLE
Individual testing is failing on import

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1083]
`linchpin/tests/README.rst` says that specifig tests could be run with `nosetests` command, for example `nosetests -vv -s linchpin/tests/cli`, but it fails on import (ansible):

```
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
Failure: ImportError (No module named ansible) ... ERROR
Failure: ImportError (No module named ansible) ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named ansible)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/abraverm/.nextcloud/contribute/linchpin/linchpin/tests/cli/test_context_pass.py", line 22, in <module>
    from linchpin.cli.context import LinchpinCliContext
  File "/home/abraverm/.nextcloud/contribute/linchpin/linchpin/__init__.py", line 15, in <module>
    from linchpin.ansible_runner import ansible_runner
  File "/home/abraverm/.nextcloud/contribute/linchpin/linchpin/ansible_runner.py", line 3, in <module>
    import ansible
ImportError: No module named ansible

======================================================================
ERROR: Failure: ImportError (No module named ansible)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/abraverm/.nextcloud/contribute/linchpin/linchpin/tests/cli/tests_init_pass.py", line 10, in <module>
    from linchpin import LinchpinAPI
  File "/home/abraverm/.nextcloud/contribute/linchpin/linchpin/__init__.py", line 15, in <module>
    from linchpin.ansible_runner import ansible_runner
  File "/home/abraverm/.nextcloud/contribute/linchpin/linchpin/ansible_runner.py", line 3, in <module>
    import ansible
ImportError: No module named ansible

----------------------------------------------------------------------
Ran 2 tests in 0.013s

FAILED (errors=2)
```
This doesn't happen when running `python setup.py test`.

**Comment by samvarankashyap** [comment]
@abraverm : What is the ansible version you are using? 
It seems to be either ansible is not installed or ansible has removed ansible library from a certain version

**Comment by abraverm** [comment]
I have ansible installed in the virtual environment, and it resolved with running `pip install -e .` in linchpin directory

**Comment by abraverm** [comment]
Just to be clear:
```bash
$ pip list | grep ansible
ansible                       2.7.4 
```

**Comment by samvarankashyap** [comment]
python -c "import ansible; print(ansible.__version__)"

**Comment by samvarankashyap** [comment]
@abraverm Further, could you try upgrading ansible and rerunning tests. And see if the error still persists

**Comment by abraverm** [comment]
```bash
➜ python -c "import ansible; print(ansible.__version__)"
2.7.4
```
I've updated to 2.7.10, same error

**Comment by abraverm** [comment]
Figured it out:
`~/.pyenv/shims/nosetests -vv -s linchpin/tests/cli`

**Comment by abraverm** [comment]
The weird part is
```
➜ which nosetests
~/.pyenv/shims/nosetests
```
