### ISSUE TITLE
Need support for ansible 2.8.x

### ISSUE THREAD

**Issue by amolkahat** [CentOS-PaaS-SIG/linchpin#1224]
**Describe the bug**
Ansible 2.8.x and python3 support needed for linchpin.

**To Reproduce**
1. Install ansible with python3
2. Install linchpin with python3

**Expected behavior**
Linchpin should work and provision the VMs.

**Traceback**
```
# linchpin --creds-path credentials/clouds.yaml up
Traceback (most recent call last):
  File "/usr/local/bin/linchpin", line 11, in <module>
    load_entry_point('linchpin==1.7.6.1', 'console_scripts', 'linchpin')()
  File "/home/guest/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/guest/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/guest/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/guest/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/guest/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/guest/.local/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/guest/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/linchpin/shell/__init__.py", line 292, in up
    inv_f=inventory_format)
  File "/usr/local/lib/python3.7/site-packages/linchpin/cli/__init__.py", line 391, in lp_up
    tx_id=tx_id)
  File "/usr/local/lib/python3.7/site-packages/linchpin/cli/__init__.py", line 578, in _execute_action
    run_id=run_id)
  File "/usr/local/lib/python3.7/site-packages/linchpin/cli/__init__.py", line 753, in _execute
    tx_id=tx_id)
  File "/usr/local/lib/python3.7/site-packages/linchpin/__init__.py", line 622, in do_action
    console=ansible_console)
  File "/usr/local/lib/python3.7/site-packages/linchpin/__init__.py", line 930, in _invoke_playbooks
    msg = res['failed'][0]._result['msg']
KeyError: 'msg'

# ansible --version
ansible 2.8.2
  config file = None
  configured module search path = ['/home/guest/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/guest/.local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]

# linchpin --version
linchpin version 1.7.6.1
```

**Desktop (please complete the following information):**
 - RHEL-8.x, Fedora-29

**Comment by samvarankashyap** [comment]
Notes:
@amolkahat @14rcole 
I am unable to reproduce this error on fedora28, python3.6.8 and ansible version 2.8.2

**Comment by samvarankashyap** [comment]
I think its a problem with python3.7.x

**Comment by samvarankashyap** [comment]
I am unable to reproduce the same error on fedora29 ansible 2.8.2 and python 3.7.3 as mentioned in above environment. 
Could you please share the verbose output of 
```
linchpin -vvvv --creds-path credentials/clouds.yaml up
```
and also the Pinfile you are currently using?

**Comment by 14rcole** [comment]
@amolkahat I am also unable to reproduce the issue.  Can you try using the latest develop branch of linchpin (or pr #1226) and see if you're still facing the same problem?

**Comment by amolkahat** [comment]
@14rcole I used latest build ```inchpin-1.7.6.2``` and ```ansible-2.8.1``` and it is working.

**Comment by amolkahat** [comment]
Hey sorry.. I replied too soon. :confused: 

While I triggered my jobs, linchpin was running but some time later it failed with following error:
```
TASK [openstack : provision/teardown os_server resources with provided auth] ***
failed: [localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```

**Comment by 14rcole** [comment]
Can you set `debug_mode = True` in your linchpin.conf and run it again?

**Comment by samvarankashyap** [comment]
@amolkahat I think the issue is with the credentials or permissions. 
could you please try debug_mode = True and run again. 
Let us know the output.
Thanks

**Comment by amolkahat** [comment]
Hi Here is the debug_mode=True output
```
$ linchpin -vvvv --creds-path credentials/clouds.yaml up
Processing target: example_target
rundb_id: 10
uhash: 7c0a14
calling: preup
hook preup initiated
statically imported: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/gather_resources/tasks/update_async_outputs.yml
statically imported: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/gather_resources/tasks/update_os_server_outputs.yml
statically imported: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/gather_resources/tasks/update_os_obj_outputs.yml
statically imported: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/gather_resources/tasks/update_os_volume_outputs.yml
statically imported: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/gather_resources/tasks/update_os_heat_outputs.yml
statically imported: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/gather_resources/tasks/update_aws_ec2_outputs.yml
statically imported: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/gather_resources/tasks/update_gcloud_gce_outputs.yml
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.7/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: openstack.yml *******************************************************************************************************************************************************************************************
connection: local
module_path: ('/home/akahat/.config/linchpin/linchpin-x/library/', '/usr/local/lib/python3.7/site-packages/linchpin/provision/library/')
forks: 100
become_method: sudo
become_user: root
verbosity: 4
3 plays in /usr/local/lib/python3.7/site-packages/linchpin/provision/openstack.yml

PLAY [schema check and Pre-Provisioning Activities on topology_file] **********************************************************************************************************************************************
META: ran handlers

TASK [common : assign async value] ********************************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/common/tasks/main.yml:2
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [common : declare async_types array] *************************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/common/tasks/main.yml:7
[DEPRECATION WARNING]: evaluating _async as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. 
This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [common : output vars] ***************************************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/common/tasks/main.yml:13
ok: [localhost] => {
    "ansible_facts": {
        "topology_outputs": {}
    },
    "changed": false
}
META: ran handlers
META: ran handlers

PLAY [Provisioning openstack resources] ***************************************************************************************************************************************************************************
META: ran handlers

TASK [openstack : declaring output vars] **************************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/main.yml:7
ok: [localhost] => {
    "ansible_facts": {
        "topology_outputs_os_heat": [],
        "topology_outputs_os_keypair": [],
        "topology_outputs_os_network": [],
        "topology_outputs_os_object": [],
        "topology_outputs_os_server": [],
        "topology_outputs_os_sg": [],
        "topology_outputs_os_volume": []
    },
    "changed": false
}

TASK [openstack : Initiating Provision/Teardown of openstack resource group] **************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/main.yml:17
included: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml for localhost

TASK [openstack : Unset the authvar from previous run] ************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:2
ok: [localhost] => {
    "ansible_facts": {
        "auth_var": ""
    },
    "changed": false
}

TASK [openstack : set default_cred_profile when res_grp[credentials] is undefined] ********************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:6
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [openstack : set default_cred_profile when res_grp[credentials] is undefined] ********************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:11
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [openstack : set cred_profile when res_grp[credentials] is defined] ******************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:16
ok: [localhost] => {
    "ansible_facts": {
        "cred_profile": "devstack"
    },
    "changed": false
}

TASK [openstack : set default_cred_filename when res_grp[credentials] is defined] *********************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:21
ok: [localhost] => {
    "ansible_facts": {
        "cred_filename": "clouds.yaml"
    },
    "changed": false
}

TASK [openstack : Get creds from auth driver] *********************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:26
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: akahat
<localhost> EXEC /bin/sh -c 'echo ~akahat && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/akahat/.ansible/tmp/ansible-tmp-1563891173.3093379-105999416567311 `" && echo ansible-tmp-1563891173.3093379-105999416567311="` echo /home/akahat/.ansible/tmp/ansible-tmp-1563891173.3093379-105999416567311 `" ) && sleep 0'
Using module file /usr/local/lib/python3.7/site-packages/linchpin/provision/library/auth_driver.py
<localhost> PUT /home/akahat/.ansible/tmp/ansible-local-5122el80si0n/tmpt3e11ial TO /home/akahat/.ansible/tmp/ansible-tmp-1563891173.3093379-105999416567311/AnsiballZ_auth_driver.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/akahat/.ansible/tmp/ansible-tmp-1563891173.3093379-105999416567311/ /home/akahat/.ansible/tmp/ansible-tmp-1563891173.3093379-105999416567311/AnsiballZ_auth_driver.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/akahat/.ansible/tmp/ansible-tmp-1563891173.3093379-105999416567311/AnsiballZ_auth_driver.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/akahat/.ansible/tmp/ansible-tmp-1563891173.3093379-105999416567311/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
    "changed": false
}
...ignoring

TASK [openstack : set auth_var] ***********************************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:39
skipping: [localhost] => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
    "changed": false
}

TASK [openstack : provisioning resource definitions of current group] *********************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:46
included: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml for localhost

TASK [openstack : Set os_res_type value] **************************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:2
[DEPRECATION WARNING]: evaluating _async as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. 
This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [openstack : Add resource type to async_types] ***************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:7
[DEPRECATION WARNING]: evaluating _async as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. 
This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [openstack : Get the resource name] **************************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:12
ok: [localhost] => {
    "ansible_facts": {
        "os_resource_name": "master",
        "unique_name": false
    },
    "changed": false
}

TASK [openstack : Create name using uhash value] ******************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:17
[DEPRECATION WARNING]: evaluating unique_name as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration 
toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [openstack : provision/teardown resources] *******************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:22
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [openstack : provision/teardown resources] *******************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:26
included: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml for localhost

TASK [openstack : set_fact for res_def] ***************************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:1
ok: [localhost] => {
    "ansible_facts": {
        "res_def_add_vol": [],
        "res_def_names": []
    },
    "changed": false
}

TASK [openstack : generate res_def_names] *************************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:6
skipping: [localhost] => (item=0)  => {
    "ansible_loop_var": "inst_c",
    "changed": false,
    "inst_c": "0",
    "skip_reason": "Conditional result was False"
}

TASK [openstack : generate res_def_names] *************************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:14
ok: [localhost] => {
    "ansible_facts": {
        "res_def_names": [
            "master"
        ]
    },
    "changed": false
}

TASK [openstack : set_fact instance filters] **********************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:19
ok: [localhost] => {
    "ansible_facts": {
        "res_def_prov": [
            {
                "name": "master"
            }
        ]
    },
    "changed": false
}

TASK [openstack : set_fact when addtional volumes] ****************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:23
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [openstack : Provision additional volumes] *******************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:28

TASK [openstack : Detach additional volumes] **********************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:41

TASK [openstack : Delete additional volumes] **********************************************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:53

TASK [openstack : provision/teardown os_server resources with provided auth] **************************************************************************************************************************************
task path: /usr/local/lib/python3.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:63
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: akahat
<localhost> EXEC /bin/sh -c 'echo ~akahat && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/akahat/.ansible/tmp/ansible-tmp-1563891175.11526-90221698912207 `" && echo ansible-tmp-1563891175.11526-90221698912207="` echo /home/akahat/.ansible/tmp/ansible-tmp-1563891175.11526-90221698912207 `" ) && sleep 0'
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/cloud/openstack/os_server.py
<localhost> PUT /home/akahat/.ansible/tmp/ansible-local-5122el80si0n/tmpluncga4x TO /home/akahat/.ansible/tmp/ansible-tmp-1563891175.11526-90221698912207/AnsiballZ_os_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/akahat/.ansible/tmp/ansible-tmp-1563891175.11526-90221698912207/ /home/akahat/.ansible/tmp/ansible-tmp-1563891175.11526-90221698912207/AnsiballZ_os_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/akahat/.ansible/tmp/ansible-tmp-1563891175.11526-90221698912207/AnsiballZ_os_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/akahat/.ansible/tmp/ansible-tmp-1563891175.11526-90221698912207/ > /dev/null 2>&1 && sleep 0'
failed: [localhost] (item=None) => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
    "changed": false
}
fatal: [localhost]: FAILED! => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
    "changed": false
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=13   changed=0    unreachable=0    failed=1    skipped=14   rescued=0    ignored=1   

Unsuccessful provision of resource

linchpin-openstack $ 
```

**Comment by 14rcole** [comment]
I'm still confused as to why this is happening:
```
failed: [localhost] (item=None) => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
    "changed": false
}
```
`no_log` should only be true when `debug_mode = False` and it's preventing us from seeing the actual issue.  Further, I can't reproduce the issue on my machine.  Can you provide your PinFile?

**Comment by samvarankashyap** [comment]
ping @amolkahat Any update with the latest release of linchpin 1.8.1 ??

**Comment by amolkahat** [comment]
@samvarankashyap @14rcole Hey.. I'm still able to see the issue. 

```
$ linchpin --creds-path credentials/clouds.yaml up
[DEPRECATION WARNING]: evaluating _async as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. 
This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: evaluating _async as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. 
This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: evaluating _async as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. 
This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: evaluating unique_name as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration 
toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
Traceback (most recent call last):
  File "/usr/local/bin/linchpin", line 11, in <module>
    load_entry_point('linchpin==1.7.6.2', 'console_scripts', 'linchpin')()
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/linchpin/shell/__init__.py", line 296, in up
    inv_f=inventory_format)
  File "/usr/local/lib/python3.7/site-packages/linchpin/cli/__init__.py", line 391, in lp_up
    tx_id=tx_id)
  File "/usr/local/lib/python3.7/site-packages/linchpin/cli/__init__.py", line 578, in _execute_action
    run_id=run_id)
  File "/usr/local/lib/python3.7/site-packages/linchpin/cli/__init__.py", line 753, in _execute
    tx_id=tx_id)
  File "/usr/local/lib/python3.7/site-packages/linchpin/__init__.py", line 631, in do_action
    console=ansible_console)
  File "/usr/local/lib/python3.7/site-packages/linchpin/__init__.py", line 939, in _invoke_playbooks
    msg = res['failed'][0]._result['msg']
KeyError: 'msg'

 $ ansible --version
ansible 2.8.4
  config file = None
  configured module search path = ['/home/akahat/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/akahat/.local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]

$ linchpin --version
linchpin version 1.7.6.2
```

**Comment by samvarankashyap** [comment]
@amolkahat quick question: which operating system are you currently running on?

**Comment by samvarankashyap** [comment]
> @amolkahat quick question: which operating system are you currently running on?

Nvm I see you are running rhel8 and fedora29

**Comment by samvarankashyap** [comment]
@amolkahat 
I tried reproducing the issue on fedora30 and ansible 2.8.4 and linchpin 1.8.1 python 3.7
with following Pinfile
```yaml
dummy-topo:
  topology:
    topology_name: "dummy_cluster" # topology name
    resource_groups:
      - resource_group_name: "dummy"
        resource_group_type: "dummy"
        resource_definitions:
          - name: "{{ distro | default('') }}web"
            role: "dummy_node"
            count: 3
          - name: "{{ distro | default('') }}test"
            role: "dummy_node"
            count: 1
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
      hosts:
        example-node:
          count: 3
          host_groups:
            - example
        test-node:
          count: 1
          host_groups:
            - test
```
I am Unable to reproduce the bug. 
Could you try the above Pinfile and see if it is running? 
Further,
Could you share the Pinfile you are running? 
Sometimes uninstalling and reinstalling linchpin also helps.
have you installed python3-devel packages before installing linchpin ?
```
pip3 uninstall linchpin
pip3 install linchpin
```
Let me know if you face any problems.

**Comment by 14rcole** [comment]
I still can't reproduce the issue with your PinFile, on either Fedora 29 or Fedora 30.  I was using Python 2.7 and Ansible 2.8.4 if that helps

**Comment by samvarankashyap** [comment]
Closing this issue. Due to a lack of feedback. 
please feel free to re-open the issue if necessary
