### ISSUE TITLE
Future python 2.7 module missing with linchpin 1.7.6.2

### ISSUE THREAD

**Issue by ssegalredhat** [CentOS-PaaS-SIG/linchpin#1269]
**Describe the bug**

Linchpin 1.7.6.2 fails on RHEL 7.6 with Python 2.7:
 Traceback (most recent call last):
  File "/usr/bin/linchpin", line 7, in <module>
    from linchpin.shell import runcli
  File "/usr/lib/python2.7/site-packages/linchpin/__init__.py", line 19, in <module>
    from linchpin.hooks.state import State
  File "/usr/lib/python2.7/site-packages/linchpin/hooks/__init__.py", line 52, in <module>
    import git
  File "/usr/lib/python2.7/site-packages/git/__init__.py", line 46, in <module>
    from git.repo import Repo               # @NoMove @IgnorePep8
  File "/usr/lib/python2.7/site-packages/git/repo/__init__.py", line 4, in <module>
    from .base import *
  File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 7, in <module>
    from builtins import str
ImportError: No module named builtins

**To Reproduce**
1. on RHEL 7.6, install linchpin 1.7.6.2 - pip install linchpin==1.7.6.2
2. linchpin -w linchpin-openstack -p PinFile.fedora --creds-path linchpin-openstack/credentials -v up
**Expected behavior**
Will not fail on missing module

**Comment by samvarankashyap** [comment]
@ssegalredhat
It should work once you install future package
```
pip install future
```

**Comment by ssegalredhat** [comment]
@samvarankashyap yers, but it should be installed as dependency when I install linchpin, no?

**Comment by samvarankashyap** [comment]
@ssegalredhat 
I agree with you. 
However, Due to the lack of testing on rhel images we were not aware of that. 
Will try to fix this in next release.

**Comment by samvarankashyap** [comment]
@ssegalredhat #1270 should fix this issue

**Comment by samvarankashyap** [comment]
fixed by #1270
