### ISSUE TITLE
RFE - Support concurrent transactions when saving data to RunDB

### ISSUE THREAD

**Issue by Dannyb48** [CentOS-PaaS-SIG/linchpin#1406]
**Is your feature request related to a problem? Please describe.**
I had a user deploying 6-7 VMs using Carbon & Linchpin but kept intermittently running into errors similar to the below excerpt. In the past I've seen this as well and sometimes the very nature of deleting the rundb file and letting linchpin recreate it goes away. 

My theory in this case is that LInchpin/TinyDB through this error because I think two Linchpin processes were trying to run the playbook to update the rundb with their topo output. 

Let me explain a little how carbon works. When provisioning, each resource is assigned its own provisioning task, and our provision tasks get injected with a provisioner implementation(i.e. Linchpin). In this case, each task will have their own instance of a provisioner. What happens is that carbon will send these tasks to an execution library that can either execute them concurrently (using multiprocessing) or sequentially. By default provisioning in Carbon is concurrent to be able to speed up the provisioning phase. So in this user's case we had 6 different provisioning processes calling Linchpin API independently. It looked like two of the processes clashed getting to the point of having topo data written to rundb.

As a workaround I had the user enable the provision task in carbon to be sequential and did not run into the errors below. They are going to do some more testing to be sure. 

`019-10-16 08:34:45,477 ERROR Extra data: line 1 column 33680 - line 1 column 33716 (char 33679 - 33715)
2019-10-16 08:34:45,477 ERROR Failed to provision asset OCPonOSP_logging_reg_master5ffc61
2019-10-16 08:34:45,487 ERROR Extra data: line 1 column 33680 - line 1 column 33716 (char 33679 - 33715)
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/blaster/engine/parallel.py", line 50, in run
    value = getattr(task_obj, method)()
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/carbon/tasks/provision.py", line 80, in run
    return self.provisioner.create()
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/carbon/provisioners/asset_provisioner.py", line 137, in create
    res = self.plugin.create()
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/carbon/provisioners/ext/linchpin_wrapper_plugin.py", line 357, in create
    res = self._create()
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/carbon/provisioners/ext/linchpin_wrapper_plugin.py", line 257, in _create
    tx_id, ('inputs', 'outputs'))
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/linchpin/__init__.py", line 789, in get_run_data
    record = rundb.get_tx_record(tx_id)
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/linchpin/rundb/basedb.py", line 31, in get_tx_record
    return self.driver.get_tx_record(tx_id)
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/linchpin/rundb/tinyrundb.py", line 13, in func_wrapper
    args[0]._opendb()
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/linchpin/rundb/tinyrundb.py", line 32, in _opendb
    default_table=self.default_table)
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/tinydb/database.py", line 167, in __init__
    self._table = self.table(default_table)
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/tinydb/database.py", line 203, in table
    **table_kwargs)
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/tinydb/database.py", line 309, in __init__
    data = self._read()
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/tinydb/database.py", line 411, in _read
    return self._storage.read()
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/tinydb/database.py", line 90, in read
    raw_data = self._storage.read() or {}
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/tinydb/middlewares.py", line 96, in read
    self.cache = self.storage.read()
  File "/var/lib/jenkins/workspace/REG-OCP3.10-Logging-OSP/scenario/lib/python2.7/site-packages/tinydb/storages.py", line 116, in read
    return json.load(self._handle)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 33680 - line 1 column 33716 (char 33679 - 33715)`

**Describe the solution you'd like**
My understanding is that TinyDB does not have ACID functionality. We could employ File Level locking from Carbon, which we already have that capability, but I don't think it would make sense here because it would be too course grain. We would have to create the file lock BEFORE we call the linchpin API, and then it wouldn't release the lock until the linchpin API returned. Essentially blocking the processes. To me it would make more sense to the have the file level locking in the RunDB implementation within Linchpin to make up for the lack of locking available in TinyDB.

**Comment by Dannyb48** [comment]
This is going to warrant a bigger discussion in the team but I figured I would file this just to get the conversation started.

**Comment by Dannyb48** [comment]
@samvarankashyap I know Ryan is working on the enabling the use of other drivers, like mongodb, but are you still going to increase the cache size for the current TinyDB implementation?

**Comment by 14rcole** [comment]
@Dannyb48 I thought that the issue with concurrency in TinyDB is that our updates require reading, doing manual changes, then an update since TinyDB doesn't support complex queries.  We can support concurrency with file locking if you'd like

We can also add another driver if you prefer that, the first two are always the hardest

**Comment by Dannyb48** [comment]
@14rcole Oh ok, I didn't realize that the update required a reading before the writing. 
I like the direction of the approach, abstracting it so that back-end databases can be plugged in. I think the MongoDB is a good add as well. By all means I'm not diminishing the work you got done. 

I'm just thinking that for concurrency support using Carbon w/Linchpin would now require another component, like MongoDB. Which I find *heavy* for lack of better term. I would think MongoDB would be something we would want to jump to when we get to the point of scale and performance on par with a hosted web service. That being said, this could be my perception because Carbon, by itself, is still pretty lightweight. Our persistence layer is very minimal, we just use a file. We really just write out a copy of the source yaml file with specific key fields updated or added that get used later on. So for me it's a little hesitant. 

Any chance we can also look at SQlite support? SQLite is small enough like TinyDB but offers concurrency/threading support?

**Comment by 14rcole** [comment]
@Dannyb48 I was considering that issue when I was writing this.  I started with mongodb because I had some experience with pymongo, but I was considering adding sqlite after.  I can definitely take that on in the next sprint

**Comment by samvarankashyap** [comment]
closing #1471 #1515 
fixes this issue
