### ISSUE TITLE
linchpin Openstack vm  provisioning fails with  below error

### ISSUE THREAD

**Issue by maveric-tellrv** [CentOS-PaaS-SIG/linchpin#1427]
**Describe the bug**

linchpin Openstack vm  provision fails with  below error

```
TASK [openstack : provision/teardown os_server resources with provided auth] *****************************************************************************************************************************************************************
task path: /root/test/testscripts/src/script/linchpin/openstack/.linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:121
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051 `" && echo ansible-tmp-1571928272.08-64283766791051="` echo /root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051 `" ) && sleep 0'
Using module file /root/test/testscripts/src/script/linchpin/openstack/.linchpin/lib/python2.7/site-packages/ansible/modules/cloud/openstack/os_server.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-24218uqGf7H/tmpSmuDQE TO /root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/AnsiballZ_os_server.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/ /root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/AnsiballZ_os_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/root/test/testscripts/src/script/linchpin/openstack/.linchpin/bin/python2.7 /root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/AnsiballZ_os_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/AnsiballZ_os_server.py", line 114, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/AnsiballZ_os_server.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/AnsiballZ_os_server.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_os_server_payload_OA9RvP/__main__.py", line 753, in <module>
  File "/tmp/ansible_os_server_payload_OA9RvP/__main__.py", line 744, in main
  File "/tmp/ansible_os_server_payload_OA9RvP/__main__.py", line 541, in _create_server
  File "/tmp/ansible_os_server_payload_OA9RvP/__main__.py", line 417, in _exit_hostvars
  File "/root/test/testscripts/src/script/linchpin/openstack/.linchpin/lib/python2.7/site-packages/openstack/cloud/_compute.py", line 1832, in get_openstack_vars
    return meta.get_hostvars_from_server(self, server)
  File "/root/test/testscripts/src/script/linchpin/openstack/.linchpin/lib/python2.7/site-packages/openstack/cloud/meta.py", line 487, in get_hostvars_from_server
    flavor_id = server['flavor']['id']
KeyError: 'id'

failed: [localhost] (item=RHEL8_397382) => {
    "ansible_loop_var": "prov_inst", 
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/AnsiballZ_os_server.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/AnsiballZ_os_server.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1571928272.08-64283766791051/AnsiballZ_os_server.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_os_server_payload_OA9RvP/__main__.py\", line 753, in <module>\n  File \"/tmp/ansible_os_server_payload_OA9RvP/__main__.py\", line 744, in main\n  File \"/tmp/ansible_os_server_payload_OA9RvP/__main__.py\", line 541, in _create_server\n  File \"/tmp/ansible_os_server_payload_OA9RvP/__main__.py\", line 417, in _exit_hostvars\n  File \"/root/test/testscripts/src/script/linchpin/openstack/.linchpin/lib/python2.7/site-packages/openstack/cloud/_compute.py\", line 1832, in get_openstack_vars\n    return meta.get_hostvars_from_server(self, server)\n  File \"/root/test/testscripts/src/script/linchpin/openstack/.linchpin/lib/python2.7/site-packages/openstack/cloud/meta.py\", line 487, in get_hostvars_from_server\n    flavor_id = server['flavor']['id']\nKeyError: 'id'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "prov_inst": "RHEL8_397382", 
    "rc": 1
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=14   changed=0    unreachable=0    failed=1    skipped=15   rescued=0    ignored=1   


Unsuccessful provision of resource
```

**PINFILE used:**

```
simple:
  topology:
    topology_name: simple
    resource_groups:
      - resource_group_name: os_simple
        resource_group_type: openstack
        resource_definitions:
          - name: "RHEL8"
            role: os_server
            flavor: m1.medium
            keypair: el8build
            count: 1
            image: RHEL-8.0.0-x86_64-production-latest
            networks:
              - provider_net_quicklab
            userdata: |
              #cloud-config
              chpasswd:
                list: |
                  root:{{ redhat }}
                expire: False
              packages:
                - git
                - python27-python-pip
                - make
                - rpmbuild
            availability_zone: nova
        credentials:
          filename: playbooks/clouds.yaml
          profile: openstack
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
      hosts:
        RHEL8:
          count: 1
          host_groups:
          - RHEL8

```

```
***linchpin --version** 
**_linchpin version 1.8.2_**
(.linchpin) [root@vm15 openstack]# ansible --version 
**_ansible 2.8.4_**
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/test/testscripts/src/script/linchpin/openstack/.linchpin/lib/python2.7/site-packages/ansible
  executable location = /root/test/testscripts/src/script/linchpin/openstack/.linchpin/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

**Comment by samvarankashyap** [comment]
During the initial investigations, it was found out that there is bug with the latest versions of openstack SDK is not working anymore with shade package which ansible uses for openstack provisioning. @maveric-tellrv 
current workaround will be restricting version of openstacksdk to 0.26 

```
pip install openstacksdk==0.26 
```
I will be soon following up with PR and filing issues with shade and OpenStack SDK. 

Thank you for reporting the issue.

**Comment by maveric-tellrv** [comment]
@samvarankashyap Thanks !  Workaround resolves this  issue.
