### ISSUE TITLE
missing module 'json'

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1504]
**Describe the bug**
Linchpin callback.py fails to import when installed with python 2.7 and Ansible 2.9:
```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1575287003.01-223577331376831/AnsiballZ_rundb.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1575287003.01-223577331376831/AnsiballZ_rundb.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1575287003.01-223577331376831/AnsiballZ_rundb.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.rundb', init_globals=None, run_name='__main__', alter_sys=False)
  File "/usr/lib64/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_rundb_payload_14JBq_/ansible_rundb_payload.zip/ansible/modules/rundb.py", line 9, in <module>
  File "//opt/linchpin/lib/python2.7/site-packages/linchpin-1.9.0.1-py2.7.egg/linchpin/__init__.py", line 17, in <module>
    from linchpin.ansible_runner import ansible_runner
  File "//opt/linchpin/lib/python2.7/site-packages/linchpin-1.9.0.1-py2.7.egg/linchpin/ansible_runner.py", line 22, in <module>
    from .callbacks import PlaybookCallback
  File "//opt/linchpin/lib/python2.7/site-packages/linchpin-1.9.0.1-py2.7.egg/linchpin/callbacks.py", line 2, in <module>
    from ansible.plugins.callback import CallbackBase
  File "//opt/linchpin/lib/python2.7/site-packages/ansible/plugins/callback/__init__.py", line 34, in <module>
    from ansible.parsing.ajson import AnsibleJSONEncoder
  File "//opt/linchpin/lib/python2.7/site-packages/ansible/parsing/ajson.py", line 11, in <module>
    from ansible.module_utils.common.json import AnsibleJSONEncoder
ImportError: No module named json
```

**To Reproduce**
1. Create Python 2.7 virtual environment and install linchpin (make sure it has Ansible 2.9 installed too)
2. Run Linchpin up with some non dummy provider like AWS
3. Ansible will fail on task "gather_resources : Add topology_outputs to the rundb"

**Comment by 14rcole** [comment]
We keep thinking we've fixed this only to have it crop up again.  Also, are you sure it doesn't show up on dummy?

**Comment by abraverm** [comment]
AFAIR from the investigation I did this morning, but it failed for sure when I tried with AWS.

**Comment by Dannyb48** [comment]
our nightly carbon job just ran into this for openstack provider

```
2019-12-03 01:10:37,259 INFO 
TASK [gather_resources : Add topology_outputs to the rundb] ********************

2019-12-03 01:10:39,852 INFO An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.common.json'

```

**Comment by 14rcole** [comment]
Which version of Ansible are you each using?

**Comment by abraverm** [comment]
Ansible 2.9, python 2.7

**Comment by Dannyb48** [comment]
Ansible 2.9, python 3.6

**Comment by samvarankashyap** [comment]
@Dannyb48 Operating system?

**Comment by Dannyb48** [comment]
@samvarankashyap the source container image our ci image is based on is RHEL7 jenkins

**Comment by 14rcole** [comment]
@Dannyb48 @abraverm 2.9.0 or 2.9.1?

**Comment by samvarankashyap** [comment]
@14rcole It should be 2.9.0 since we restrict linchpin to 2.9.0

**Comment by samvarankashyap** [comment]
Unable to reproduce on :
```
centos7, python 2.7.16 
fedora30, python 3.7.5
```

**Comment by samvarankashyap** [comment]
@Dannyb48 @abraverm @14rcole 
I was able to reproduce error inside a python3.6 virtualenv. 
These are the following steps i followed to reproduce the error:

- create a python3 virtualenv

```
python3 -m venv myvenv 
```

- activate virtualenv 
```
source ./myvenv/bin/activate 
```
- install linchpin from source code
```
git clone https://github.com/CentOS-PaaS-SIG/linchpin
cd linchpin 
pip3 install -e file://$PWD 
```
- go to openstack-mock workspace 
```
cd docs/source/examples/workspaces/openstack
```
- run linchpin up 
```
linchpin -vvvv up 
```

Error observed on debug mode is as follows :
```
TASK [gather_resources : Add topology_outputs to the rundb] ******************************************************************************************************
task path: /home/srallaba/myenv/lib/python3.6/site-packages/linchpin/provision/roles/gather_resources/tasks/main.yml:160
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: srallaba
<127.0.0.1> EXEC /bin/sh -c 'echo ~srallaba && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756 `" && echo ansible-tmp-1575424936.956834-240434834581756="` echo /home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756 `" ) && sleep 0'
Using module file /home/srallaba/myenv/lib/python3.6/site-packages/linchpin/provision/library/rundb.py
<127.0.0.1> PUT /home/srallaba/.ansible/tmp/ansible-local-32737bzc1kjz1/tmp5atz6tzs TO /home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/AnsiballZ_rundb.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/ /home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/AnsiballZ_rundb.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/srallaba/myenv/bin/python3 /home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/AnsiballZ_rundb.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_rundb_payload_ulfjaj71/ansible_rundb_payload.zip/ansible/modules/rundb.py", line 13, in <module>
  File "/tmp/ansible_rundb_payload_ulfjaj71/ansible_rundb_payload.zip/ansible/module_utils/rundb/mongodb.py", line 10, in <module>
ModuleNotFoundError: No module named 'pymongo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/srallaba/myenv/lib64/python3.6/site-packages/linchpin/ansible_runner.py", line 17, in <module>
    from .callbacks import PlaybookCallback
  File "/home/srallaba/myenv/lib64/python3.6/site-packages/linchpin/callbacks.py", line 2, in <module>
    from ansible.plugins.callback import CallbackBase
  File "/home/srallaba/myenv/lib64/python3.6/site-packages/ansible/plugins/callback/__init__.py", line 34, in <module>
    from ansible.parsing.ajson import AnsibleJSONEncoder
  File "/home/srallaba/myenv/lib64/python3.6/site-packages/ansible/parsing/ajson.py", line 11, in <module>
    from ansible.module_utils.common.json import AnsibleJSONEncoder
ModuleNotFoundError: No module named 'ansible.module_utils.common.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/AnsiballZ_rundb.py", line 102, in <module>
    _ansiballz_main()
  File "/home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/AnsiballZ_rundb.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/AnsiballZ_rundb.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.rundb', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_rundb_payload_ulfjaj71/ansible_rundb_payload.zip/ansible/modules/rundb.py", line 15, in <module>
  File "/home/srallaba/myenv/lib64/python3.6/site-packages/linchpin/__init__.py", line 21, in <module>
    from linchpin.ansible_runner import ansible_runner
  File "/home/srallaba/myenv/lib64/python3.6/site-packages/linchpin/ansible_runner.py", line 22, in <module>
    from .callbacks import PlaybookCallback
  File "/home/srallaba/myenv/lib64/python3.6/site-packages/linchpin/callbacks.py", line 2, in <module>
    from ansible.plugins.callback import CallbackBase
  File "/home/srallaba/myenv/lib64/python3.6/site-packages/ansible/plugins/callback/__init__.py", line 34, in <module>
    from ansible.parsing.ajson import AnsibleJSONEncoder
  File "/home/srallaba/myenv/lib64/python3.6/site-packages/ansible/parsing/ajson.py", line 11, in <module>
    from ansible.module_utils.common.json import AnsibleJSONEncoder
ModuleNotFoundError: No module named 'ansible.module_utils.common.json'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_rundb_payload_ulfjaj71/ansible_rundb_payload.zip/ansible/modules/rundb.py\", line 13, in <module>\n  File \"/tmp/ansible_rundb_payload_ulfjaj71/ansible_rundb_payload.zip/ansible/module_utils/rundb/mongodb.py\", line 10, in <module>\nModuleNotFoundError: No module named 'pymongo'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/srallaba/myenv/lib64/python3.6/site-packages/linchpin/ansible_runner.py\", line 17, in <module>\n    from .callbacks import PlaybookCallback\n  File \"/home/srallaba/myenv/lib64/python3.6/site-packages/linchpin/callbacks.py\", line 2, in <module>\n    from ansible.plugins.callback import CallbackBase\n  File \"/home/srallaba/myenv/lib64/python3.6/site-packages/ansible/plugins/callback/__init__.py\", line 34, in <module>\n    from ansible.parsing.ajson import AnsibleJSONEncoder\n  File \"/home/srallaba/myenv/lib64/python3.6/site-packages/ansible/parsing/ajson.py\", line 11, in <module>\n    from ansible.module_utils.common.json import AnsibleJSONEncoder\nModuleNotFoundError: No module named 'ansible.module_utils.common.json'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/AnsiballZ_rundb.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/AnsiballZ_rundb.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/srallaba/.ansible/tmp/ansible-tmp-1575424936.956834-240434834581756/AnsiballZ_rundb.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.rundb', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_rundb_payload_ulfjaj71/ansible_rundb_payload.zip/ansible/modules/rundb.py\", line 15, in <module>\n  File \"/home/srallaba/myenv/lib64/python3.6/site-packages/linchpin/__init__.py\", line 21, in <module>\n    from linchpin.ansible_runner import ansible_runner\n  File \"/home/srallaba/myenv/lib64/python3.6/site-packages/linchpin/ansible_runner.py\", line 22, in <module>\n    from .callbacks import PlaybookCallback\n  File \"/home/srallaba/myenv/lib64/python3.6/site-packages/linchpin/callbacks.py\", line 2, in <module>\n    from ansible.plugins.callback import CallbackBase\n  File \"/home/srallaba/myenv/lib64/python3.6/site-packages/ansible/plugins/callback/__init__.py\", line 34, in <module>\n    from ansible.parsing.ajson import AnsibleJSONEncoder\n  File \"/home/srallaba/myenv/lib64/python3.6/site-packages/ansible/parsing/ajson.py\", line 11, in <module>\n    from ansible.module_utils.common.json import AnsibleJSONEncoder\nModuleNotFoundError: No module named 'ansible.module_utils.common.json'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *******************************************************************************************************************************************************
localhost                  : ok=21   changed=1    unreachable=0    failed=1    skipped=51   rescued=0    ignored=1   

```

If you see closely it is failing to import pymongo package. Which is causing the error. 

- Now i went ahead and installed pymongo using pip3 within the same virtualenv. 
```
pip3 install pymongo
```

and I ran the same provision 
```
linchpin -vvvv up os-server-new 
```
output was successfull 
```
TASK [gather_resources : Add inventory_path to outputs] ***********************************************************************************************************************************
task path: /home/srallaba/myenv/lib/python3.6/site-packages/linchpin/provision/roles/gather_resources/tasks/main.yml:212
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: srallaba
<127.0.0.1> EXEC /bin/sh -c 'echo ~srallaba && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/srallaba/.ansible/tmp/ansible-tmp-1575425100.3700838-201512602918774 `" && echo ansible-tmp-1575425100.3700838-201512602918774="` echo /home/srallaba/.ansible/tmp/ansible-tmp-1575425100.3700838-201512602918774 `" ) && sleep 0'
Using module file /home/srallaba/myenv/lib/python3.6/site-packages/linchpin/provision/library/rundb.py
<127.0.0.1> PUT /home/srallaba/.ansible/tmp/ansible-local-555e33efr3n/tmpnwyq43md TO /home/srallaba/.ansible/tmp/ansible-tmp-1575425100.3700838-201512602918774/AnsiballZ_rundb.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/srallaba/.ansible/tmp/ansible-tmp-1575425100.3700838-201512602918774/ /home/srallaba/.ansible/tmp/ansible-tmp-1575425100.3700838-201512602918774/AnsiballZ_rundb.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/srallaba/myenv/bin/python3 /home/srallaba/.ansible/tmp/ansible-tmp-1575425100.3700838-201512602918774/AnsiballZ_rundb.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/srallaba/.ansible/tmp/ansible-tmp-1575425100.3700838-201512602918774/ > /dev/null 2>&1 && sleep 0'
[WARNING]: The value [{'inventory_path': ['/home/srallaba/linchpin/docs/source/examples/workspaces/openstack/inventories/os-server-new-57d0e6.inventory']}] (type list) in a string field
was converted to "[{'inventory_path': ['/home/srallaba/linchpin/docs/source/examples/workspaces/openstack/inventories/os-server-new-57d0e6.inventory']}]" (type string). If this does not
look like what you expect, quote the entire value to ensure it does not change.

changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "action": "up",
            "conn_str": "/home/srallaba/.config/linchpin/rundb-90520730779204.json",
            "db_schema": {
                "action": "",
                "cfgs": [],
                "end": "",
                "hooks": [],
                "inputs": [],
                "outputs": [],
                "rc": 0,
                "start": "",
                "uhash": ""
            },
            "db_type": "TinyRunDB",
            "key": "outputs",
            "operation": "update",
            "run_id": 15,
            "table": "os-server-new",
            "value": "[{'inventory_path': ['/home/srallaba/linchpin/docs/source/examples/workspaces/openstack/inventories/os-server-new-57d0e6.inventory']}]"
        }
    },
    "output": "[15]"
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************
localhost                  : ok=28   changed=3    unreachable=0    failed=0    skipped=54   rescued=0    ignored=1   

[██████████] Linchpin(up)                  | Finishing resource group os-server-newPlaybook Return code 0
Action 'up' on Target 'os-server-new' is complete        
hook postinv initiated
hook postup initiated

ID: 7
Action: up

Target                  Run ID  uHash   Exit Code 
-------------------------------------------------
os-server-new               15  57d0e6          0

```


## Conclusion 

- since pymongo is not included in python2.7 virtual environments it failed for @abraverm 
- Since pymongo is not implicitly installed with carbon or linchpin it failed for @Dannyb48 

pymongo is the real culprit here 
even though we have included the exception handling and if conditions
it still fails with ansible since due to the fact that module utils are complied and ran.  

@Dannyb48 Could you try installing pymongo after installing linchpin inside virtualenv and try running jobs again. 

@14rcole Is there any way we can avoid using pymongo unless we specify in module utils. ??

**Comment by 14rcole** [comment]
@samvarankashyap we may be able to make the conditional import a bit more robust, I'll try something.   I'm still confused as to why @abraverm has an issue

**Comment by samvarankashyap** [comment]
@14rcole I found the fix for it 
#1515 Should fix this error.

**Comment by samvarankashyap** [comment]
@14rcole @abraverm @Dannyb48 
Notes From #1515 PR 

Ansible does not allow imports which are nonexistent in the python environment within module_utils
and causes JSON error as a side effect since module_utils are not loaded.

The above fix is a hack for #1504
I could not find any better solution at this point in time.

Note:
Further, one should have a clean installation of linchpin.
Since if we try installing linchpin again in existing virtualenv it won't work.
existing linchpin should be uninstalled using

pip3 uninstall linchpin
@Dannyb48 Let me know if it works
@abraverm ^^^ this should work with both python3 and python2 envs

**Comment by Dannyb48** [comment]
@samvarankashyap nice work! I will kick it off now.

**Comment by Dannyb48** [comment]
@samvarankashyap @14rcole this might be silly question and it could be my lack of ansible module development experience but do we import all the rundb packages again, create the DB_driver method again, and instantiate another instance of rundb in the rundb.py library?

an instance of the rundb with a proper driver is already instantiated in the Linchpin __init__.py. Is there any way we can inject that rundb instance into the rundb.py anisble library? Either pass it in as one of the Ansible Module parameters? or have a helper function that the rundb.py could get import that could return the rundb instance the __init__.py created?

**Comment by 14rcole** [comment]
I don't know if we can pass an object as one of the Ansible module parameters, but I can look into it.  The rundb module would still have to import from linchpin's rundb though so I don't know that that would solve the problem

**Comment by samvarankashyap** [comment]
@Dannyb48 I agree with @14rcole
