### ISSUE TITLE
Nightly downstream job failing with LinchpinAPI import errors

### ISSUE THREAD

**Issue by Dannyb48** [CentOS-PaaS-SIG/linchpin#1549]
**Describe the bug**
Our jobs are failing with the failing with the following error

```
 File "/home/jenkins/workspace/Carbon-Linchpin-Nightly/cbn/lib/python2.7/site-packages/carbon/provisioners/ext/linchpin_wrapper_plugin.py", line 83, in __init__
    self.linchpin_api = LinchpinAPI(self._init_context())
NameError: global name 'LinchpinAPI' is not defined
```

This is using latest development branch and python 2.7. 

If open up a python console and try to perform the same import, I get the following error messages about the mock library, which I think is causing the import of the API to not work. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dbaez/.virtualenvs/linchpin-nightly/lib/python2.7/site-packages/linchpin/__init__.py", line 20, in <module>
    from mock import MagicMock
ImportError: No module named mock
```
 
**To Reproduce**
1. Install latest develop branch `pip install git+https://github.com/CentOS-PaaS-SIG/linchpin.git@develop`
2. open python console `python`
3. import the LinchpinAPI `from linchpin import LinchpinAPI`

**Comment by samvarankashyap** [comment]
@Dannyb48  #1551 should fix this import error.
