### ISSUE TITLE
linchpin setup commands fail with a ValueError

### ISSUE THREAD

**Issue by Dannyb48** [CentOS-PaaS-SIG/linchpin#1582]
**Describe the bug**

OS: Fedora 28
python: 3.6.8
linchpin: latest

Trying to run setup commands `linchpin setup` or `linchpin setup beaker` fails with the following error:

```
(lp-py3) [dbaez@dbaez_fedora_laptop beaker]$ linchpin setup beaker
- downloading role 'setup', owned by 
[WARNING]: - setup was NOT installed successfully: None (HTTP Code: 400, Message: Unknown error returned by Galaxy server.)

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
Traceback (most recent call last):
  File "/home/dbaez/.virtualenvs/lp-py3/bin/linchpin", line 11, in <module>
    load_entry_point('linchpin', 'console_scripts', 'linchpin')()
  File "/home/dbaez/.virtualenvs/lp-py3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dbaez/.virtualenvs/lp-py3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dbaez/.virtualenvs/lp-py3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dbaez/.virtualenvs/lp-py3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dbaez/.virtualenvs/lp-py3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dbaez/.virtualenvs/lp-py3/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/dbaez/.virtualenvs/lp-py3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dbaez/projects/lp-py3/linchpin/linchpin/shell/__init__.py", line 685, in setup
    return_code, output = lpcli.lp_setup(providers)
  File "/home/dbaez/projects/lp-py3/linchpin/linchpin/cli/__init__.py", line 482, in lp_setup
    action="setup")
  File "/home/dbaez/projects/lp-py3/linchpin/linchpin/__init__.py", line 1021, in _invoke_playbooks
    console=console)
  File "/home/dbaez/projects/lp-py3/linchpin/linchpin/__init__.py", line 957, in _find_n_run_pb
    self._get_role(pb_name)
  File "/home/dbaez/projects/lp-py3/linchpin/linchpin/__init__.py", line 322, in _get_role
    " Galaxy".format(role, self.role_path))
ValueError: unmatched '{' in format spec

```

I think this might be caused by a typo in the actual error message trying to be displayed

```
raise LinchpinError("role '{0]' not found in path: {1}\n. It also"
                                " could not be installed via Ansible"
                                " Galaxy".format(role, self.role_path))
```

Notice how the place holder 0 is wrapped in part curly brace and part square bracket. 

**To Reproduce**
1. `pip install linchpin`
2. `linchpin setup beaker`
3. See error

**Comment by 14rcole** [comment]
I've got a fix for this, but it looks like the Ansible Galaxy stuff broke linchpin setup in general, so I'll post a PR once I fix that too

**Comment by samvarankashyap** [comment]
@14rcole Any update on this issue? 
Do you still have the fix ready

**Comment by 14rcole** [comment]
Yeah, I submitted the PR a while back, I'm not sure what number it was
