### ISSUE TITLE
linchpin does not run when installed via RPM on CentOS7

### ISSUE THREAD

**Issue by arilivigni** [CentOS-PaaS-SIG/linchpin#1586]
**Describe the bug**
When building a Jenkins CentOS7 slave image openshift/jenkins-slave-maven-centos7:v3.11
I believe @p3ck also hit this but not in a container

**To Reproduce**
Steps to reproduce the behavior - Dockerfile:

```
FROM openshift/jenkins-slave-maven-centos7:v3.11

USER root

# Setup RH-IT-Root-CA certificate for RedHat
RUN curl --insecure \
        -L https://password.corp.redhat.com/RH-IT-Root-CA.crt \
        -o /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt \
    && update-ca-trust extract \

# install RCM tools to get brew CLI
    && curl --insecure \
           -L http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-7-workstation.repo \
           -o /etc/yum.repos.d/rcm-tools-rhel-7-workstation.repo

# Install packages
RUN yum install -y epel-release \
        && yum install -y \
        koji brewkoji brewkoji-stage \
        gcc \
        jq \
        ruby \
        python-devel \
        python-pip \
        nmap-ncat \
        openldap-clients \
        krb5-workstation \
        file \
        skopeo \
        python2-wheel \
        python2-setuptools \
        python-urllib3 \
        python-pygit2 \
        python2-openshift \
        python2-kubernetes \
        ansible \
        yum-plugin-copr \
    && yum copr enable -y alexbmasis/linchpin \
    && yum install -y linchpin \
    && yum clean all

# Install client 3.11
RUN mkdir /oc \
    && curl --insecure \
            -L https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz \
            -o /tmp/oc.tar.gz \
    && mkdir -p /oc/3.11.0/ \
    && tar xvfz /tmp/oc.tar.gz -C /oc/3.11.0/ --strip-components 1 \
    && rm /tmp/oc.tar.gz \
    # fix the koji/brew wrapper. Changing the python3 back to python2 is needed as centos-7 does not have python3
    # TODO remove the line below once the issue is fixed (should be in version brewkoji-1.22-1.el7)
    && sed -i 's/#!\/usr\/bin\/env python3/#!\/usr\/bin\/env python2/g' /bin/brew

COPY redhat_com /etc/krb5.conf.d/

## Copy run to /tmp/bin/run
## It can be used as an entrypoint/command
## in a containerTemplate.
## We make use of it when using this image
## as the ansible-executor
#
## This is needed for 2 reasons:
## 1. It creates the required entry in /etc/passwd for
##    the user running the container. Ansible requires it.
##    e.x. KeyError: 'getpwuid(): uid not found: 1000260000'
## 2. It simply starts a blocking call to keep the container running
##    so commands can be injected via the Jenkins Kubernetes plugin and 'sh'
##
COPY bin/ /tmp/bin/
COPY home/jenkins $HOME

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001
```

2. podman build . or docker build .
3. linchpin --help
bash-4.2# linchpin --help
Traceback (most recent call last):
  File "/opt/linchpin/bin/linchpin", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2489, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2700, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2724, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 30, in <lambda>
    next = lambda o: o.next()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2807, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'astroid ~=1.5.3', 'at', ' ~=1.5.3')

**Expected behavior**
linchpin runs on CentOS without a traceback

**Comment by samvarankashyap** [comment]
@arilivigni 
Thank you for reporting the issue with Linchpin RPM. 
@abraverm Is currently working on fixing linchpin RPM and also update it to the latest version. 
Currently, He is off for the weekend he will look into it on Monday and fix it as soon as possible. 

Note: 
RPM is not the official way we package linchpin in the current CI system. Moreover, installing linchpin from PyPi is a stable way. We will be making a decision on whether to have RPM packaging a part of our CI system soon.

**Comment by p3ck** [comment]
Just a note that installing linchpin from PyPi is not easily done for RHEL7/CentOS7.  If you are on this platform and do a pip install linchpin[libvirt] it will in one of two ways.

1 - If you are using python2 environment the libvirt-python package will complain that python2 is EOL and requires python3 now.
2 - If you install python3 on RHEL7/CentOS7 then you will later fail with an selinux error because there is no libselinux-python3 yet.

You can get around the above by manually installing an older version of libvirt-python. 

But I would hardly say that installing from PyPi is stable.

**Comment by maneeshmehra** [comment]
@p3ck: Does that mean that there is no python 3 support in RHEL7/CentOS7 at the moment ? Also, what you describe above, is that an issue only with the current latest version of LP or would one see that behavior even with an older version of LP (say 1.9.0 that was released last year, when python 2 was still not EOL ?

@samvarankashyap: How did we test v1.9.2 version LP in RHEL7/CentOS7 then ? What version of Python did we use to validate it in our CI pipeline ?

**Comment by p3ck** [comment]
python3 support on RHEL7/CentOS7 is incomplete if you need selinux support.
https://bugs.centos.org/view.php?id=16389
https://bugzilla.redhat.com/show_bug.cgi?id=1719978

I tried installing an older version of linchpin and the requirements are the same.

**Comment by abraverm** [comment]
The build verified (manually) on CentOS 7 and Fedora 30:
https://copr.fedorainfracloud.org/coprs/alexbmasis/linchpin-devel/build/1185281/

The RPM packages use python 2.

**Comment by samvarankashyap** [comment]
@maneeshmehra 
We use the centos7 container to validate the linchpin version. Centos7 container runs on 2.7 version of python this is because of the python3-libselinux is not available for python3 . As mentioned by @p3ck.

**Comment by samvarankashyap** [comment]
@maneeshmehra 
The following is a bug report filed on Centos upstream to incorporate python3-libselinux
https://bugs.centos.org/view.php?id=16389

**Comment by samvarankashyap** [comment]
@arilivigni @p3ck 
could you please let us you whether the latest build of linchpin 1.9.2 works for you and keep us updated if that works for you. 
Thank you. 

The build verified (manually) on CentOS 7 and Fedora 30:
https://copr.fedorainfracloud.org/coprs/alexbmasis/linchpin-devel/build/1185281/

The RPM packages use python 2.

**Comment by maneeshmehra** [comment]
@abraverm, @samvarankashyap: Don't we need to wait to see if the solution provided to the submitter (@arilivigni) works or not ? Also, don't we need to understand support for Python 3 in CentOS 7 prior to closing this issue ? Perhaps that is something to check with the submitter if they are OK with installing LinchPin on CentOS7 with Python 2 or if they definitely need Python 3 support. What do you think ?

**Comment by abraverm** [comment]
They can reopen it if it doesn't work. Its CentOS issue and there is #283 for Python 3 compatability. If the submitter needs Linchpin running on Python 3 on CentOS 7 that should have its own ticket (RFE), which will be blocked until CentOS issue resolved and #283 fixed. Finally,  anyone can continue the discussion here but it is not adviced.

**Comment by samvarankashyap** [comment]
@maneeshmehra This issue is automatically closed by the bot. 
If linchpin needs to work on centos7 with python3 then I would also recommend them to reopen the ticket. Which is usually the case with most of the tickets.

**Comment by maneeshmehra** [comment]
Sounds good. @arilivigni, @p3ck: I leave it upto you to decide on whether you are OK with the provided solution or expect more work to happen.

**Comment by maneeshmehra** [comment]
FWIW, I thought I would take the new RPM for a spin myself. I tried  to create a container image using the Dockerfile provided by @arilivigni in the description of the ticket. However, that failed with the following message:

```
Step 6/10 : COPY redhat_com /etc/krb5.conf.d/
COPY failed: stat /var/lib/docker/tmp/docker-builder481154347/redhat_com: no such file or directory
```

I then:
1. Removed all lines after the line that installs yum packages from my Dockerfile
2. Added the following as the last thing: ENTRYPOINT ["/bin/bash"]
3. Rebuilt the image

Here is what my resulting Dockerfile looked like:
```
FROM openshift/jenkins-slave-maven-centos7:v3.11

USER root

# Setup RH-IT-Root-CA certificate for RedHat
RUN curl --insecure \
        -L https://password.corp.redhat.com/RH-IT-Root-CA.crt \
        -o /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt \
    && update-ca-trust extract \

# install RCM tools to get brew CLI
    && curl --insecure \
           -L http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-7-workstation.repo \
           -o /etc/yum.repos.d/rcm-tools-rhel-7-workstation.repo

# Install packages
RUN yum install -y epel-release \
        && yum install -y \
        koji brewkoji brewkoji-stage \
        gcc \
        jq \
        ruby \
        python-devel \
        python-pip \
        nmap-ncat \
        openldap-clients \
        krb5-workstation \
        file \
        skopeo \
        python2-wheel \
        python2-setuptools \
        python-urllib3 \
        python-pygit2 \
        python2-openshift \
        python2-kubernetes \
        ansible \
        yum-plugin-copr \
    && yum copr enable -y alexbmasis/linchpin \
    && yum install -y linchpin \
    && yum clean all

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001

ENTRYPOINT ["/bin/bash"]
```

I was then able to fire up a container using this image and was able to confirm that the new RPM works:
```
[root@ibm-p8-kvm-03-guest-02 test2]# docker run -it centos7/linchpin 
bash-4.2$ which linchpin
/usr/bin/linchpin
bash-4.2$ linchpin --help
Usage: linchpin [OPTIONS] COMMAND [ARGS]...

  linchpin: hybrid cloud orchestration

Options:
  -c, --config PATH               Path to config file
  -p, --pinfile PINFILE           Use a name for the PinFile different from
                                  the configuration.
  -d, --template-data TEMPLATE_DATA
                                  Template data passed to PinFile template.
                                  If template data is from a file, it must be
                                  prepended with an '@' character.
  -o, --output-file, --output-pinfile OUTPUT_FILE
                                  Write out PinFile to provided location
  -w, --workspace PATH            Use the specified workspace. Also works if
                                  the familiar Jenkins WORKSPACE environment
                                  variable is set
  -v, --verbose                   Enable verbose output
  --version                       Prints the version and exits
  --creds-path PATH               Use the specified credentials path. Also
                                  works if CREDS_PATH environment variable is
                                  set
  --ask-vault-pass                Prompts for vault password
  --no-monitor                    Disalbe multiprocessing for monitoring
                                  Ansible execution
  -h, --help                      Show this message and exit.

Commands:
  init     Initializes a linchpin project.
  up       Provisions nodes from the given target(s) in the given PinFile.
  destroy  Destroys resources using either the run_id or tx_id (mutually...
  fetch    Fetches a specified linchpin workspace or component from a
           remote...
  journal  Display information stored in Run Database view: How the journal...
  setup    Install the dependencies needed for the given provider(s).
  ssh      SSH to deployed system
bash-4.2$ 
```

**Comment by maneeshmehra** [comment]
I should've also mentioned that linchpin gave me this upon running `linchpin --version`: 
```
bash-4.2$ linchpin --version
linchpin version 1.9.2
```
