### ISSUE TITLE
Provisioning from beaker is failed on fedora 33

### ISSUE THREAD

**Issue by yunmingyang** [CentOS-PaaS-SIG/linchpin#1767]
When provisioning machines on fedora 33, there will be an error which is "AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'" ,and the command will be terminated.

1. Prepare a VM which is fedora33, and its default version of python is 3.9
2. Prepare a python virtual environment
3. Install linchpin
4. Provision a machine from beaker

**Expected behavior**
Linchpin can work correctly on fedora 33

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Linchpin version: 2.0.4.1

**Additional context**
It seems that xml.etree.ElementTree.Element.getiterator() has been removed since python3.9
Here is the error message:
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1608139363.5240405-29567-119266629821986/AnsiballZ_bkr_server.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1608139363.5240405-29567-119266629821986/AnsiballZ_bkr_server.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1608139363.5240405-29567-119266629821986/AnsiballZ_bkr_server.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.bkr_server', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bkr_server_payload_q7h_3t5r/ansible_bkr_server_payload.zip/ansible/modules/bkr_server.py", line 333, in <module>
  File "/tmp/ansible_bkr_server_payload_q7h_3t5r/ansible_bkr_server_payload.zip/ansible/modules/bkr_server.py", line 321, in main
  File "/tmp/ansible_bkr_server_payload_q7h_3t5r/ansible_bkr_server_payload.zip/ansible/modules/bkr_server.py", line 251, in check_jobs
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'

**Comment by JunqiZhang0** [comment]
Hi @yunmingyang , is this something block your work? Linchpin is now under maintenance mode, we only support business critical bugs, you can always submit PRs, and we will review it.

**Comment by yunmingyang** [comment]
Hi, I resolve it by change the OS to fedora 32.So feel free to close the issue, thanks

**Comment by JunqiZhang0** [comment]
> Hi, I resolve it by change the OS to fedora 32.So feel free to close the issue, thanks

Thanks!
