### ISSUE TITLE
linchpin destroy duffy error after 1.0 upgrade

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#263]
Tried linchpin destroy duffy 
```
(lp-venv)[fedora-atomic@slave03 lp_workspace]$ linchpin drop duffy

PLAY [schema check and Pre Provisioning Activities on topology_file] ***********

TASK [common : use linchpin_config if provided] ********************************
skipping: [localhost]

TASK [common : set lp_path] ****************************************************
skipping: [localhost]

TASK [common : set lpconfig (linchpin.conf) full path] *************************
skipping: [localhost]

TASK [common : set boolean evars from linchpin.conf] ***************************
skipping: [localhost]

TASK [common : set schema evars from linchpin.conf] ****************************
skipping: [localhost]

TASK [common : set default path evars from linchpin.conf] **********************
skipping: [localhost]

TASK [common : set remaining evars from linchpin.conf] *************************
skipping: [localhost]

TASK [common : set default path evars using workspace var] *********************
skipping: [localhost]

TASK [common : if topology_file is passed, set topology to its value] **********
skipping: [localhost]

TASK [common : if schema_file is passed, set schema to its value] **************
skipping: [localhost]

TASK [common : check topology file against the provided schema] ****************
skipping: [localhost]

TASK [common : assign output from provided schema] *****************************
skipping: [localhost]

TASK [common : check topology file against schema_v3] **************************
ok: [localhost]

TASK [common : Set state for schema_v3 validation] *****************************
ok: [localhost]

TASK [common : assign schema_v3 output] ****************************************
ok: [localhost]

TASK [common : check topology file against schema_v4] **************************
skipping: [localhost]

TASK [common : update output when schema_v4 is used] ***************************
skipping: [localhost]

TASK [common : assign output from schema_v4] ***********************************
skipping: [localhost]

TASK [common : set fact for saving topology_job_ids] ***************************
ok: [localhost]

TASK [common : Get the resource group types defined in topology] ***************
ok: [localhost]

TASK [common : Filter resource_groups by type] *********************************
ok: [localhost]

TASK [common : Assigning facts with respect to their group type] ***************
ok: [localhost]

TASK [common : filtering the output for openshift v3] **************************
ok: [localhost]

TASK [common : filtering the output for openshift v4] **************************
skipping: [localhost]

TASK [common : Registering resource group vars from topology] ******************
skipping: [localhost]

TASK [common : output vars] ****************************************************
ok: [localhost]

PLAY [Provisioning resources based on resource group type] *********************

TASK [dummy : DEBUG:: Dummy resource group list] *******************************
skipping: [localhost]

TASK [dummy : declaring output vars] *******************************************
skipping: [localhost]

TASK [dummy : Initiating Provisioning of dummy resource group] *****************

TASK [dummy : Initiating Teardown of dummy resource group] *********************

TASK [openstack : DEBUG:: Openstack resource group list] ***********************
skipping: [localhost]

TASK [openstack : declaring output vars] ***************************************
skipping: [localhost]

TASK [openstack : Initiating  Provisioning/Deprovioning of resources Openstack resource group] ***

TASK [aws : Provisioning aws resources] ****************************************
skipping: [localhost]

TASK [aws : declaring output vars] *********************************************
skipping: [localhost]

TASK [aws : Initiating  Provisioning of resources aws resource group] **********

TASK [aws : Initiating  teardown of resources aws resource group] **************

TASK [gcloud : DEBUG:: gcloud resource group list] *****************************
skipping: [localhost]

TASK [gcloud : declaring output vars for topology outputs of gce] **************
skipping: [localhost]

TASK [gcloud : Initiating  Provisioning of resources in gcloud resource group] *

TASK [duffy : DEBUG:: Duffy resource group list] *******************************
ok: [localhost] => {
    "msg": "Currently provisioning the resources under list duffy_res_grps [{u'resource_group_name': u'duffy_1node_group', u'res_group_type': u'duffy_node', u'assoc_creds': u'duffy_creds', u'res_defs': [{u'res_name': u'duffy_nodes', u'res_type': u'duffy_node', u'version': 7, u'arch': u'x86_64', u'count': 1}]}]"
}

TASK [duffy : declaring output vars] *******************************************
ok: [localhost]

TASK [duffy : Initiating Provisioning of duffy resource group] *****************
skipping: [localhost] => (item={u'resource_group_name': u'duffy_1node_group', u'res_group_type': u'duffy_node', u'assoc_creds': u'duffy_creds', u'res_defs': [{u'res_name': u'duffy_nodes', u'res_type': u'duffy_node', u'version': 7, u'arch': u'x86_64', u'count': 1}]}) 

TASK [duffy : Initiating Teardown of duffy resource group] *********************
included: /home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/linchpin/provision/roles/duffy/tasks/teardown_resource_group.yml for localhost

TASK [duffy : DEBUG:: provisioning resource group {u'resource_group_name': u'duffy_1node_group', u'res_group_type': u'duffy_node', u'assoc_creds': u'duffy_creds', u'res_defs': [{u'res_name': u'duffy_nodes', u'res_type': u'duffy_node', u'version': 7, u'arch': u'x86_64', u'count': 1}]}] ***
skipping: [localhost]

TASK [duffy : Including credentials of current resource duffy_1node_group] *****
ok: [localhost]

TASK [duffy : Parsing topology output file] ************************************
changed: [localhost]

TASK [duffy : DEBUG:: gathering resource group data: {u'output': {u'content': {u'openshift_res': [], u'os_obj_res': [], u'os_keypair_res': [], u'duffy_res': [{u'changed': True, u'hosts': [u'n61.pufty.ci.centos.org'], u'ssid': u'b9ad81e4'}], u'aws_ec2_res': [], u'os_server_res': [], u'aws_ec2_key_res': [], u'gcloud_gce_res': [], u'aws_s3_res': [], u'aws_cfn_res': [], u'os_sg_res': [], u'dummy_res': [], u'beaker_res': [], u'os_heat_res': [], u'rax_server_res': [], u'libvirt_res': [], u'os_volume_res': []}, u'path': u'/home/fedora-atomic/ari-sandbox/lp_workspace/resources/duffy_1node.output'}, u'changed': True}] ***
ok: [localhost] => {
    "msg": "The current server obj is b9ad81e4 "
}

TASK [duffy : Teardown resource definitions of current group] ******************
included: /home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/linchpin/provision/roles/duffy/tasks/teardown_res_defs.yml for localhost

TASK [duffy : Teardown Duffy Resources] ****************************************
changed: [localhost]

TASK [libvirt : declaring output vars] *****************************************
skipping: [localhost]

TASK [libvirt : Initiating libvirt resource group] *****************************

TASK [rackspace : DEBUG:: rackspace resource group list] ***********************
skipping: [localhost]

TASK [rackspace : declaring output vars] ***************************************
skipping: [localhost]

TASK [rackspace : Initiating  Provisioning/Deprovioning of resources rackspace resource group] ***

TASK [beaker : allocate beaker outputs] ****************************************
skipping: [localhost]

TASK [beaker : debug] **********************************************************
skipping: [localhost]

TASK [beaker : provision beaker systems] ***************************************

TASK [beaker : fetch beaker details] *******************************************

TASK [beaker : debug] **********************************************************
skipping: [localhost]

TASK [beaker : append beaker outputs] ******************************************

TASK [beaker : Initiating Teardown of beaker resource group] *******************

TASK [openshift : allocate openshift output variables] *************************
skipping: [localhost]

TASK [openshift : provision openshift resources] *******************************

PLAY [Writing contents to file] ************************************************

TASK [output_writer : Updating topology_outputs] *******************************
ok: [localhost]

TASK [output_writer : Create output directories] *******************************
ok: [localhost] => (item=/home/fedora-atomic/ari-sandbox/lp_workspace/resources)
ok: [localhost] => (item=/home/fedora-atomic/ari-sandbox/lp_workspace/inventories)

TASK [output_writer : DEBUG:: topology_outputs] ********************************
ok: [localhost] => {
    "msg": {
        "aws_cfn_res": [], 
        "aws_ec2_key_res": [], 
        "aws_ec2_res": [], 
        "aws_s3_res": [], 
        "beaker_res": [], 
        "duffy_res": [], 
        "dummy_res": [], 
        "gcloud_gce_res": [], 
        "libvirt_res": [], 
        "openshift_res": [], 
        "os_heat_res": [], 
        "os_keypair_res": [], 
        "os_obj_res": [], 
        "os_server_res": [], 
        "os_sg_res": [], 
        "os_volume_res": [], 
        "rax_server_res": []
    }
}

TASK [output_writer : Generate outputs when async is false] ********************
skipping: [localhost]

TASK [output_writer : Async:: Updating topology_outputs] ***********************
skipping: [localhost]

TASK [output_writer : register var for async_outputs_os_server] ****************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_os_obj] *******************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_os_obj] *******************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_os_server] ****************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_aws_ec2] ******************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_aws_ec2] ******************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_aws_ec2] ******************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : Async:: Updating topology_outputs after wait] ************
skipping: [localhost]

TASK [output_writer : Generate outputs when async is true] *********************
skipping: [localhost]

TASK [output_writer : set name of the resources_file for inventory generation] *
skipping: [localhost]

PLAY [inventory generation role] ***********************************************

TASK [inventory_gen : include_vars] ********************************************
skipping: [localhost]

TASK [inventory_gen : Updating topology_outputs] *******************************
skipping: [localhost]

TASK [inventory_gen : Parse inventory layout as a ordered dict] ****************
skipping: [localhost]

TASK [inventory_gen : Updating inventory_file with the absolute path] **********
skipping: [localhost]

TASK [inventory_gen : Generate Generic Inventory] ******************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=20   changed=2    unreachable=0    failed=0   

Traceback (most recent call last):
  File "/home/fedora-atomic/ari-sandbox/lp-venv/bin/linchpin", line 9, in <module>
    load_entry_point('linchpin==1.0.0', 'console_scripts', 'linchpin')()
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/linchpin/__init__.py", line 263, in destroy
    results = lpcli.lp_destroy(pf_w_path, targets)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/linchpin/api/__init__.py", line 348, in lp_destroy
    return self.run_playbook(pinfile, targets, playbook="destroy")
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/linchpin/api/__init__.py", line 282, in run_playbook
    console=ansible_console)
TypeError: 'int' object is not iterable
```

**Comment by samvarankashyap** [comment]
@herlo same error with linchpin up 
```
(lp-venv)[fedora-atomic@slave03 lp_workspace]$ linchpin up duffy

PLAY [schema check and Pre Provisioning Activities on topology_file] ***********

TASK [common : use linchpin_config if provided] ********************************
skipping: [localhost]

TASK [common : set lp_path] ****************************************************
skipping: [localhost]

TASK [common : set lpconfig (linchpin.conf) full path] *************************
skipping: [localhost]

TASK [common : set boolean evars from linchpin.conf] ***************************
skipping: [localhost]

TASK [common : set schema evars from linchpin.conf] ****************************
skipping: [localhost]

TASK [common : set default path evars from linchpin.conf] **********************
skipping: [localhost]

TASK [common : set remaining evars from linchpin.conf] *************************
skipping: [localhost]

TASK [common : set default path evars using workspace var] *********************
skipping: [localhost]

TASK [common : if topology_file is passed, set topology to its value] **********
skipping: [localhost]

TASK [common : if schema_file is passed, set schema to its value] **************
skipping: [localhost]

TASK [common : check topology file against the provided schema] ****************
skipping: [localhost]

TASK [common : assign output from provided schema] *****************************
skipping: [localhost]

TASK [common : check topology file against schema_v3] **************************
ok: [localhost]

TASK [common : Set state for schema_v3 validation] *****************************
ok: [localhost]

TASK [common : assign schema_v3 output] ****************************************
ok: [localhost]

TASK [common : check topology file against schema_v4] **************************
skipping: [localhost]

TASK [common : update output when schema_v4 is used] ***************************
skipping: [localhost]

TASK [common : assign output from schema_v4] ***********************************
skipping: [localhost]

TASK [common : set fact for saving topology_job_ids] ***************************
ok: [localhost]

TASK [common : Get the resource group types defined in topology] ***************
ok: [localhost]

TASK [common : Filter resource_groups by type] *********************************
ok: [localhost]

TASK [common : Assigning facts with respect to their group type] ***************
ok: [localhost]

TASK [common : filtering the output for openshift v3] **************************
ok: [localhost]

TASK [common : filtering the output for openshift v4] **************************
skipping: [localhost]

TASK [common : Registering resource group vars from topology] ******************
skipping: [localhost]

TASK [common : output vars] ****************************************************
ok: [localhost]

PLAY [Provisioning resources based on resource group type] *********************

TASK [dummy : DEBUG:: Dummy resource group list] *******************************
skipping: [localhost]

TASK [dummy : declaring output vars] *******************************************
skipping: [localhost]

TASK [dummy : Initiating Provisioning of dummy resource group] *****************

TASK [dummy : Initiating Teardown of dummy resource group] *********************

TASK [openstack : DEBUG:: Openstack resource group list] ***********************
skipping: [localhost]

TASK [openstack : declaring output vars] ***************************************
skipping: [localhost]

TASK [openstack : Initiating  Provisioning/Deprovioning of resources Openstack resource group] ***

TASK [aws : Provisioning aws resources] ****************************************
skipping: [localhost]

TASK [aws : declaring output vars] *********************************************
skipping: [localhost]

TASK [aws : Initiating  Provisioning of resources aws resource group] **********

TASK [aws : Initiating  teardown of resources aws resource group] **************

TASK [gcloud : DEBUG:: gcloud resource group list] *****************************
skipping: [localhost]

TASK [gcloud : declaring output vars for topology outputs of gce] **************
skipping: [localhost]

TASK [gcloud : Initiating  Provisioning of resources in gcloud resource group] *

TASK [duffy : DEBUG:: Duffy resource group list] *******************************
ok: [localhost] => {
    "msg": "Currently provisioning the resources under list duffy_res_grps [{u'resource_group_name': u'duffy_1node_group', u'res_group_type': u'duffy_node', u'assoc_creds': u'duffy_creds', u'res_defs': [{u'res_name': u'duffy_nodes', u'res_type': u'duffy_node', u'version': 7, u'arch': u'x86_64', u'count': 1}]}]"
}

TASK [duffy : declaring output vars] *******************************************
ok: [localhost]

TASK [duffy : Initiating Provisioning of duffy resource group] *****************
included: /home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/linchpin/provision/roles/duffy/tasks/provision_resource_group.yml for localhost

TASK [duffy : DEBUG:: provisioning resource group {u'resource_group_name': u'duffy_1node_group', u'res_group_type': u'duffy_node', u'assoc_creds': u'duffy_creds', u'res_defs': [{u'res_name': u'duffy_nodes', u'res_type': u'duffy_node', u'version': 7, u'arch': u'x86_64', u'count': 1}]}] ***
ok: [localhost] => {
    "msg": "The current server obj is {u'resource_group_name': u'duffy_1node_group', u'res_group_type': u'duffy_node', u'assoc_creds': u'duffy_creds', u'res_defs': [{u'res_name': u'duffy_nodes', u'res_type': u'duffy_node', u'version': 7, u'arch': u'x86_64', u'count': 1}]} "
}

TASK [duffy : Including credentials of current resource duffy_1node_group] *****
ok: [localhost]

TASK [duffy : provisioning resource definitions of current group] **************
included: /home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/linchpin/provision/roles/duffy/tasks/provision_res_defs.yml for localhost

TASK [duffy : Provision duffy resources by looping on count] *******************
changed: [localhost]

TASK [duffy : set tmp var] *****************************************************
ok: [localhost]

TASK [duffy : Append outputitem to topology_outputs] ***************************
ok: [localhost]

TASK [duffy : Initiating Teardown of duffy resource group] *********************
skipping: [localhost] => (item=[{u'resource_group_name': u'duffy_1node_group', u'res_group_type': u'duffy_node', u'assoc_creds': u'duffy_creds', u'res_defs': [{u'res_name': u'duffy_nodes', u'res_type': u'duffy_node', u'version': 7, u'arch': u'x86_64', u'count': 1}]}, u'/home/fedora-atomic/ari-sandbox/lp_workspace/resources/duffy_1node.output']) 

TASK [libvirt : declaring output vars] *****************************************
skipping: [localhost]

TASK [libvirt : Initiating libvirt resource group] *****************************

TASK [rackspace : DEBUG:: rackspace resource group list] ***********************
skipping: [localhost]

TASK [rackspace : declaring output vars] ***************************************
skipping: [localhost]

TASK [rackspace : Initiating  Provisioning/Deprovioning of resources rackspace resource group] ***

TASK [beaker : allocate beaker outputs] ****************************************
skipping: [localhost]

TASK [beaker : debug] **********************************************************
skipping: [localhost]

TASK [beaker : provision beaker systems] ***************************************

TASK [beaker : fetch beaker details] *******************************************

TASK [beaker : debug] **********************************************************
skipping: [localhost]

TASK [beaker : append beaker outputs] ******************************************

TASK [beaker : Initiating Teardown of beaker resource group] *******************

TASK [openshift : allocate openshift output variables] *************************
skipping: [localhost]

TASK [openshift : provision openshift resources] *******************************

PLAY [Writing contents to file] ************************************************

TASK [output_writer : Updating topology_outputs] *******************************
ok: [localhost]

TASK [output_writer : Create output directories] *******************************
ok: [localhost] => (item=/home/fedora-atomic/ari-sandbox/lp_workspace/resources)
ok: [localhost] => (item=/home/fedora-atomic/ari-sandbox/lp_workspace/inventories)

TASK [output_writer : DEBUG:: topology_outputs] ********************************
ok: [localhost] => {
    "msg": {
        "aws_cfn_res": [], 
        "aws_ec2_key_res": [], 
        "aws_ec2_res": [], 
        "aws_s3_res": [], 
        "beaker_res": [], 
        "duffy_res": [
            {
                "changed": true, 
                "hosts": [
                    "n45.pufty.ci.centos.org"
                ], 
                "ssid": "fb6f594d"
            }
        ], 
        "dummy_res": [], 
        "gcloud_gce_res": [], 
        "libvirt_res": [], 
        "openshift_res": [], 
        "os_heat_res": [], 
        "os_keypair_res": [], 
        "os_obj_res": [], 
        "os_server_res": [], 
        "os_sg_res": [], 
        "os_volume_res": [], 
        "rax_server_res": []
    }
}

TASK [output_writer : Generate outputs when async is false] ********************
changed: [localhost]

TASK [output_writer : Async:: Updating topology_outputs] ***********************
skipping: [localhost]

TASK [output_writer : register var for async_outputs_os_server] ****************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_os_obj] *******************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_os_obj] *******************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_os_server] ****************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_aws_ec2] ******************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_aws_ec2] ******************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : register var for async_outputs_aws_ec2] ******************
skipping: [localhost]

TASK [output_writer : Wait on jobs] ********************************************

TASK [output_writer : Async:: Updating topology_outputs after wait] ************
skipping: [localhost]

TASK [output_writer : Generate outputs when async is true] *********************
skipping: [localhost]

TASK [output_writer : set name of the resources_file for inventory generation] *
ok: [localhost]

PLAY [inventory generation role] ***********************************************

TASK [inventory_gen : include_vars] ********************************************
ok: [localhost]

TASK [inventory_gen : Updating topology_outputs] *******************************
skipping: [localhost]

TASK [inventory_gen : Parse inventory layout as a ordered dict] ****************
ok: [localhost]

TASK [inventory_gen : Updating inventory_file with the absolute path] **********
ok: [localhost]

TASK [inventory_gen : Generate Generic Inventory] ******************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=27   changed=3    unreachable=0    failed=0   

Traceback (most recent call last):
  File "/home/fedora-atomic/ari-sandbox/lp-venv/bin/linchpin", line 9, in <module>
    load_entry_point('linchpin==1.0.0', 'console_scripts', 'linchpin')()
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/linchpin/__init__.py", line 207, in up
    results = lpcli.lp_up(pf_w_path, targets)
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/linchpin/api/__init__.py", line 321, in lp_up
    return self.run_playbook(pinfile, targets, playbook="up")
  File "/home/fedora-atomic/ari-sandbox/lp-venv/lib/python2.7/site-packages/linchpin/api/__init__.py", line 282, in run_playbook
    console=ansible_console)
TypeError: 'int' object is not iterable
```

**Comment by samvarankashyap** [comment]
@herlo 
```
note: I enabled ansible console = True in linchpin.conf 
```
that might be a reason
