### ISSUE TITLE
Can't install linchpin from source on a CentOS7 system 

### ISSUE THREAD

**Issue by arilivigni** [CentOS-PaaS-SIG/linchpin#302]
```
(linchpin) $ git clone git://github.com/CentOS-PaaS-SIG/linch-pin
..snip..
(linchpin) $ pip install ./linch-pin

pip install ./linch-pin-latest
Unpacking ./linch-pin-latest
  Running setup.py egg_info for package from file:///home/sig-paas/ari_sandbox/linch-pin-latest
    
    Installed /tmp/easy_install-of72yL/shade-1.22.2/pbr-3.1.1-py2.7.egg
    Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/easy_install-of72yL/shade-1.22.2/pbr-3.1.1-py2.7.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/easy_install-of72yL/shade-1.22.2/pbr-3.1.1-py2.7.egg/pbr/util.py", line 251, in cfg_to_args
        kwargs = setup_cfg_to_setup_kwargs(config, script_args)
      File "/tmp/easy_install-of72yL/shade-1.22.2/pbr-3.1.1-py2.7.egg/pbr/util.py", line 434, in setup_cfg_to_setup_kwargs
        if pkg_resources.evaluate_marker('(%s)' % env_marker):
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 1364, in evaluate_marker
        return interpret(parser.expr(text).totuple(1)[1])
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 1342, in interpret
        return op(nodelist)
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 1307, in atom
        return interpret(nodelist[2])
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 1342, in interpret
        return op(nodelist)
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 1324, in comparison
        raise SyntaxError(repr(cop)+" operator not allowed in environment markers")
    SyntaxError: '<' operator not allowed in environment markers
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-KjEv81-build/setup.py", line 45, in <module>
        scripts=['scripts/linchpin_complete.sh']
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error in setup command: Error parsing /tmp/easy_install-of72yL/shade-1.22.2/setup.cfg: SyntaxError: '<' operator not allowed in environment markers
    Complete output from command python setup.py egg_info:
    

Installed /tmp/easy_install-of72yL/shade-1.22.2/pbr-3.1.1-py2.7.egg

Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker

ERROR:root:Error parsing

Traceback (most recent call last):

  File "/tmp/easy_install-of72yL/shade-1.22.2/pbr-3.1.1-py2.7.egg/pbr/core.py", line 111, in pbr

    attrs = util.cfg_to_args(path, dist.script_args)

  File "/tmp/easy_install-of72yL/shade-1.22.2/pbr-3.1.1-py2.7.egg/pbr/util.py", line 251, in cfg_to_args

    kwargs = setup_cfg_to_setup_kwargs(config, script_args)

  File "/tmp/easy_install-of72yL/shade-1.22.2/pbr-3.1.1-py2.7.egg/pbr/util.py", line 434, in setup_cfg_to_setup_kwargs

    if pkg_resources.evaluate_marker('(%s)' % env_marker):

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 1364, in evaluate_marker

    return interpret(parser.expr(text).totuple(1)[1])

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 1342, in interpret

    return op(nodelist)

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 1307, in atom

    return interpret(nodelist[2])

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 1342, in interpret

    return op(nodelist)

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 1324, in comparison

    raise SyntaxError(repr(cop)+" operator not allowed in environment markers")

SyntaxError: '<' operator not allowed in environment markers

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-KjEv81-build/setup.py", line 45, in <module>

    scripts=['scripts/linchpin_complete.sh']

  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve

    dist = best[req.key] = env.best_match(req, self, installer)

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain

    return installer(requirement)

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg

    return cmd.easy_install(req)

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/home/sig-paas/ari_sandbox/venv-lp-latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error in setup command: Error parsing /tmp/easy_install-of72yL/shade-1.22.2/setup.cfg: SyntaxError: '<' operator not allowed in environment markers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-KjEv81-build
```

**Comment by arilivigni** [comment]
It works if you run ./install.sh since the order in requirements is kept consistent.
I know if I install the pip module it would just work but was curious of installing from source which is still inconsistent AFAIK.

**Comment by herlo** [comment]
This has not been an issue on my Fedora machines for some time. It's clearly an issue with older deps. We've been fighting the pinning vs not pinning argument for some time. I think it may be time to separate things out into individual subpackages within linchpin. 

@samvarankashyap do you have any thoughts on this? It's similar in form to #303.

**Comment by herlo** [comment]
It appears the reason for this is that setuptools is too old on the CentOS 7 system. I ran into a similar situation with Debian on travis-ci. I fixed it by performing the following:

```
$ pip install -U setuptools
$ pip install -U pip
```

After doing this, the installation worked just fine without the install.sh. I am not certain the pip upgrade is necessary, but it didn't hurt anything.
