### ISSUE TITLE
(2) linchpin is failing with ansible 2.4

### ISSUE THREAD

**Issue by lukas-bednar** [CentOS-PaaS-SIG/linchpin#367]
when running cinchpin it fails on import error
```
(cinch)-bash-4.2$ cinchpin up -w /tmp/
Traceback (most recent call last):
  File "/var/lib/jenkins/opt/cinch/bin/linchpin", line 7, in <module>
    from linchpin import runcli
  File "/var/lib/jenkins/opt/cinch/lib/python2.7/site-packages/linchpin/__init__.py", line 7, in <module>
    from linchpin.cli import LinchpinCli
  File "/var/lib/jenkins/opt/cinch/lib/python2.7/site-packages/linchpin/cli/__init__.py", line 8, in <module>
    from linchpin.api import LinchpinAPI
  File "/var/lib/jenkins/opt/cinch/lib/python2.7/site-packages/linchpin/api/__init__.py", line 11, in <module>
    from ansible.inventory import Inventory
ImportError: cannot import name Inventory
```
ansible version
```
(cinch)-bash-4.2$ ansible --version
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/var/lib/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/jenkins/opt/cinch/lib/python2.7/site-packages/ansible
  executable location = /var/lib/jenkins/opt/cinch/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```
when downgrading to ansible-2.3.2.0 it goes OK

```
(cinch)-bash-4.2$ pip list
ansible (2.4.0.0)
apache-libcloud (2.2.0)
appdirs (1.4.3)
asn1crypto (0.22.0)
Babel (2.5.1)
bcrypt (3.1.3)
beaker-client (24.2)
beaker-common (24.2)
boto (2.48.0)
camel (0.1.2)
Cerberus (1.1)
certifi (2017.7.27.1)
cffi (1.11.0)
chardet (3.0.4)
cinch (0.8.3)
click (6.7)
cliff (2.8.0)
cmd2 (0.7.7)
cryptography (2.0.3)
debtcollector (1.17.0)
decorator (4.1.2)
deprecation (1.0.1)
dogpile.cache (0.6.4)
enum34 (1.1.6)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.1.1)
idna (2.6)
ipaddress (1.0.18)
iso8601 (0.1.12)
Jinja2 (2.9.6)
jmespath (0.9.3)
jsonpatch (1.16)
jsonpointer (1.12)
jsonschema (2.6.0)
keystoneauth1 (3.2.0)
linchpin (1.0.3)
lxml (4.0.0)
MarkupSafe (1.0)
monotonic (1.3)
msgpack-python (0.4.8)
munch (2.2.0)
Naked (0.1.31)
netaddr (0.7.19)
netifaces (0.10.6)
openstacksdk (0.9.18)
os-client-config (1.28.0)
osc-lib (1.7.0)
oslo.config (4.12.0)
oslo.i18n (3.18.0)
oslo.serialization (2.20.0)
oslo.utils (3.29.0)
paramiko (2.3.0)
pbr (3.1.1)
pip (9.0.1)
plumbum (1.6.3)
positional (1.2.1)
prettytable (0.7.2)
pyasn1 (0.3.5)
pycparser (2.18)
pycrypto (2.6.1)
PyNaCl (1.1.2)
pyOpenSSL (17.3.0)
pyparsing (2.2.0)
pyperclip (1.5.27)
python-cinderclient (3.2.0)
python-glanceclient (2.8.0)
python-ironicclient (1.17.0)
python-keystoneclient (3.13.0)
python-krbV (1.0.90)
python-novaclient (9.1.0)
python-openstackclient (3.12.0)
pytz (2017.2)
PyYAML (3.12)
requests (2.18.4)
requestsexceptions (1.3.0)
rfc3986 (1.1.0)
setuptools (36.5.0)
shade (1.23.0)
simplejson (3.11.1)
six (1.11.0)
stevedore (1.26.0)
unicodecsv (0.14.1)
urllib3 (1.22)
warlock (1.2.0)
wheel (0.30.0)
wrapt (1.10.11)
yamlordereddictloader (0.4.0)
```

**Comment by herlo** [comment]
I also discovered this yesterday. The Ansible 2.4 code changes how they manage inventories, which breaks linchpin. For now, please use Ansible 2.3.x and we'll address this bug ASAP.

**Comment by samvarankashyap** [comment]
@lukas-bednar  #369 fixes this issue , 
Please let us know if PR #369  does not.
