### ISSUE TITLE
linchpin up fails on mac - No module named yaml

### ISSUE THREAD

**Issue by cmoulliard** [CentOS-PaaS-SIG/linchpin#377]
Here is the project that I'm using on macos + instructions followed to install it, create file and start it

https://github.com/cmoulliard/provision_vm_linchpin

Ansible version installed : 2.4.0
Linchpin : 1.0.4

```
ansible --version
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/dabou/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dabou/.virtualenvs/linchpin/lib/python2.7/site-packages/ansible
  executable location = /Users/dabou/.virtualenvs/linchpin/bin/ansible
  python version = 2.7.13 (default, Jun 29 2017, 09:36:50) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

Error reported when linchpin up

```
linchpin -v up               
ctx.workspace: /Users/dabou/Temp/to-be-deleted/provision_vm
from_api: True
calling: preup
hook preup initiated
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: Found variable using reserved name: async

 [WARNING]: Found variable using reserved name: check_mode


PLAY [schema check and Pre Provisioning Activities on topology_file] ******************************************************************************************************************************************************************************************

TASK [common : use linchpin_config if provided] ***************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set lp_path] ***********************************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set lpconfig (linchpin.conf) full path] ********************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set boolean evars from linchpin.conf] **********************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set schema evars from linchpin.conf] ***********************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set default path evars from linchpin.conf] *****************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set remaining evars from linchpin.conf] ********************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set default path evars using workspace var] ****************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : if topology_file is passed, set topology to its value] *****************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : if schema_file is passed, set schema to its value] *********************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : check topology file against the provided schema] ***********************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : assign output from provided schema] ************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : check topology file against schema_v3] *********************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named yaml
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/56/dtp67r4n1hv79q2hrh_dbwcc0000gn/T/ansible_kUQp9q/ansible_module_schema_check.py\", line 10, in <module>\n    import yaml\nImportError: No module named yaml\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
...ignoring

TASK [common : Set state for schema_v3 validation] ************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [common : assign schema_v3 output] ***********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : check topology file against schema_v4] *********************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named yaml
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/56/dtp67r4n1hv79q2hrh_dbwcc0000gn/T/ansible_oZ7YLk/ansible_module_schema_check.py\", line 10, in <module>\n    import yaml\nImportError: No module named yaml\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
        to retry, use: --limit @/Users/dabou/.virtualenvs/linchpin/lib/python2.7/site-packages/linchpin/provision/site.retry

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

The pyyaml package is well installed 

```
pip install pyyaml          
Requirement already satisfied: pyyaml in /Users/dabou/.virtualenvs/linchpin/lib/python2.7/site-packages
```

**Comment by herlo** [comment]
Could this be an SELinux issue maybe? We've sometimes seen when a file cannot be read or written that selinux is preventing it in some way. One thing that doesn't get installed by pypi because it's not packaged that way is the libselinux-python packages. They also have to be symlinked into your virtualenv. 

Have a look at https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/scripts/install_libvirt_deps.sh and try out the selinux bits. Let us know if that helps.

**Comment by greg-hellings** [comment]
If OP is on Mac, then it's not an SELinux issue.

**Comment by herlo** [comment]
@greg-hellings Yeah. We spend a good amount of time on it on Friday in IRC. I failed to update here. Thanks!

**Comment by cmoulliard** [comment]
Is there a trick to similate what ansible is doing here to get more trace and check why python classpath doesn't work propertly here ?

```
TASK [common : check topology file against schema_v4] *********************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named yaml
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/56/dtp67r4n1hv79q2hrh_dbwcc0000gn/T/ansible_oZ7YLk/ansible_module_schema_check.py\", line 10, in <module>\n    import yaml\nImportError: No module named yaml\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
        to retry, use: --limit @/Users/dabou/.virtualenvs/linchpin/lib/python2.7/site-packages/linchpin/provision/site.retry
```

**Comment by herlo** [comment]
You can run your topology and/or layout files against ansible directly. I do this by going to the linchpin/provision directory and running something like this:

```
ansible-playbook -vvvv site.yml -e "topology_file='/home/herlo/Projects/rework_lp_cli/workspace/topologies/example-topology.yml'" -e "layout_file='/path/to/layout_file.yml' -e 'state=present'
```
However, when we were working through this issue on IRC, I tried this and didn't run into any errors. I do wonder if it does anything on the mac, though.

**Comment by cmoulliard** [comment]
@herlo Do you have an example about site.xml ? Which info does it contain ?

**Comment by cmoulliard** [comment]
Site.xml is part of the linch-pin project ;-)

Can we pass as -e param the credentials required by openstack ?

```
ansible-playbook -vvvv /Users/dabou/Temp/to-be-deleted/linchpin/linchpin/provision/site.yml -e "topology_file='/Users/dabou/MyProjects/provision_vm/ws/topologies/openstack-single.yml'" -e "layout_file='/Users/dabou/MyProjects/provision_vm/ws/layout/openstack-single.yml'" -e 'state=present'
...
<127.0.0.1> EXEC /bin/sh -c '/Users/dabou/.virtualenvs/linchpin/bin/python2.7 /Users/dabou/.ansible/tmp/ansible-tmp-1508411195.62-4679082511106/os_server2.py; rm -rf "/Users/dabou/.ansible/tmp/ansible-tmp-1508411195.62-4679082511106/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/56/dtp67r4n1hv79q2hrh_dbwcc0000gn/T/ansible_dbiy4n/ansible_module_os_server2.py", line 799, in <module>
    main()
  File "/var/folders/56/dtp67r4n1hv79q2hrh_dbwcc0000gn/T/ansible_dbiy4n/ansible_module_os_server2.py", line 781, in main
    cloud = shade.openstack_cloud(**cloud_params)
  File "/Users/dabou/.virtualenvs/linchpin/lib/python2.7/site-packages/shade/__init__.py", line 109, in openstack_cloud
    cloud_config = config.get_one_cloud(**kwargs)
  File "/Users/dabou/.virtualenvs/linchpin/lib/python2.7/site-packages/os_client_config/config.py", line 1074, in get_one_cloud
    auth_plugin = loader.load_from_options(**config['auth'])
  File "/Users/dabou/.virtualenvs/linchpin/lib/python2.7/site-packages/keystoneauth1/loading/base.py", line 162, in load_from_options
    raise exceptions.MissingRequiredOptions(missing_required)
keystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/56/dtp67r4n1hv79q2hrh_dbwcc0000gn/T/ansible_dbiy4n/ansible_module_os_server2.py\", line 799, in <module>\n    main()\n  File \"/var/folders/56/dtp67r4n1hv79q2hrh_dbwcc0000gn/T/ansible_dbiy4n/ansible_module_os_server2.py\", line 781, in main\n    cloud = shade.openstack_cloud(**cloud_params)\n  File \"/Users/dabou/.virtualenvs/linchpin/lib/python2.7/site-packages/shade/__init__.py\", line 109, in openstack_cloud\n    cloud_config = config.get_one_cloud(**kwargs)\n  File \"/Users/dabou/.virtualenvs/linchpin/lib/python2.7/site-packages/os_client_config/config.py\", line 1074, in get_one_cloud\n    auth_plugin = loader.load_from_options(**config['auth'])\n  File \"/Users/dabou/.virtualenvs/linchpin/lib/python2.7/site-packages/keystoneauth1/loading/base.py\", line 162, in load_from_options\n    raise exceptions.MissingRequiredOptions(missing_required)\nkeystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by cmoulliard** [comment]
This command is working 

```
ansible-playbook -vvvv /Users/dabou/Temp/to-be-deleted/linchpin/linchpin/provision/site.yml 
-e "topology_file='/Users/dabou/MyProjects/provision_vm/ws/topologies/openstack-single.yml'" 
-e "layout_file='/Users/dabou/MyProjects/provision_vm/ws/layout/openstack-single.yml'" 
-e 'state=present' 
-e 'creds_path=/Users/dabou/MyProjects/provision_vm/ws/credentials/'
```

**Comment by herlo** [comment]
@cmoulliard this implies only that the topology didn't validate against v3 of the schema we use. Further down, there's another validation for schema_v4. If that one fails (which is what you reported above), then there's trouble. The json module is still the issue here. We troubleshot it the other day, but still can't seem to figure out what's happening as I've not been able to reproduce it here.

**Comment by cmoulliard** [comment]
I don't have any issue when I start/launch linchpin without virtualenv
