### ISSUE TITLE
fails on centos6

### ISSUE THREAD

**Issue by p3ck** [CentOS-PaaS-SIG/linchpin#405]
Using python2.6 on Centos6 still fails with the following error.  This is using the latest develop branch commit f144ae91294c3604ee61c861b52310491ae862e1

```
linchpin up dummy
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. The next version of cryptography will drop support for Python 2.6
  DeprecationWarning
/usr/lib/python2.6/site-packages/linchpin/api/context.py:89: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  config = ConfigParser.SafeConfigParser()
/usr/lib/python2.6/site-packages/linchpin/api/context.py:91: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(f)
/usr/lib/python2.6/site-packages/tinydb/database.py:49: DeprecationWarning: eids has been renamed to doc_ids
  warnings.warn('eids has been renamed to doc_ids', DeprecationWarning)
[DEPRECATION WARNING]: Included file '/usr/lib/python2.6/site-
packages/linchpin/provision/update_aws_cfn_outputs.yml' not found, however since this
 include is not explicitly marked as 'static: yes', we will try and include it 
dynamically later. In the future, this will be an error unless 'static: no' is used 
on the include task. If you do not want missing includes to be considered dynamic, 
use 'static: yes' on the include or set the global ansible.cfg options to make all 
inclues static for tasks and/or handlers.
This feature will be removed in a future 
release. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.
Traceback (most recent call last):
  File "/usr/bin/linchpin", line 11, in <module>
    load_entry_point('linchpin==1.0.4', 'console_scripts', 'linchpin')()
  File "/usr/lib/python2.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/linchpin/__init__.py", line 208, in up
    return_code, results = lpcli.lp_up(pf_w_path, targets, run_id=run_id)
  File "/usr/lib/python2.6/site-packages/linchpin/api/__init__.py", line 245, in lp_up
    return self.run_playbook(pinfile, targets, action="up", run_id=run_id)
  File "/usr/lib/python2.6/site-packages/linchpin/api/__init__.py", line 617, in run_playbook
    console=ansible_console)
  File "/usr/lib/python2.6/site-packages/linchpin/api/__init__.py", line 667, in _invoke_playbook
    console=console)
  File "/usr/lib/python2.6/site-packages/linchpin/api/ansible_runner.py", line 188, in ansible_runner
    return_code = pbex.run()
  File "/usr/lib/python2.6/site-packages/ansible/executor/playbook_executor.py", line 153, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_queue_manager.py", line 257, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/__init__.py", line 353, in get
    path = self.find_plugin(name)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/__init__.py", line 263, in find_plugin
    for path in (p for p in self._get_paths() if p not in self._searched_paths and os.path.isdir(p)):
  File "/usr/lib/python2.6/site-packages/ansible/plugins/__init__.py", line 194, in _get_paths
    ret.extend(self._get_package_paths(subdirs=subdirs))
  File "/usr/lib/python2.6/site-packages/ansible/plugins/__init__.py", line 157, in _get_package_paths
    m = __import__(self.package)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/strategy/__init__.py", line 35, in <module>
    from ansible.executor.process.worker import WorkerProcess
  File "/usr/lib/python2.6/site-packages/ansible/executor/process/worker.py", line 33, in <module>
    from Crypto.Random import atfork
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
    from Crypto.Util.number import ceil_shift, exact_log2, exact_div
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
```

**Comment by herlo** [comment]
@p3ck can you check the version of PyCrypto installed? I'm wondering if it is even installed or what here?

`pip freeze | grep -i pycrypto` should help.

**Comment by p3ck** [comment]
pycrypto==2.6.1
