### ISSUE TITLE
1.2.0 failure in Centos7

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#411]
Here's the run log from my Jenkins job:
```
18:05:23 + linchpin -vvvv up x86_64-slave
18:05:25 ctx.workspace: /tmp/workspace/multiarch-qe/provision-multiarch-slave
18:05:25 from_api: True
18:05:25 Traceback (most recent call last):
18:05:25   File "/usr/bin/linchpin", line 11, in <module>
18:05:25     sys.exit(runcli())
18:05:25   File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
18:05:25     return self.main(*args, **kwargs)
18:05:25   File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
18:05:25     rv = self.invoke(ctx)
18:05:25   File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
18:05:25     return _process_result(sub_ctx.command.invoke(sub_ctx))
18:05:25   File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
18:05:25     return ctx.invoke(self.callback, **ctx.params)
18:05:25   File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
18:05:25     return callback(*args, **kwargs)
18:05:25   File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
18:05:25     return ctx.invoke(f, obj, *args[1:], **kwargs)
18:05:25   File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
18:05:25     return callback(*args, **kwargs)
18:05:25   File "/usr/lib/python2.7/site-packages/linchpin/__init__.py", line 208, in up
18:05:25     return_code, results = lpcli.lp_up(pf_w_path, targets, run_id=run_id)
18:05:25   File "/usr/lib/python2.7/site-packages/linchpin/api/__init__.py", line 245, in lp_up
18:05:25     return self.run_playbook(pinfile, targets, action="up", run_id=run_id)
18:05:25   File "/usr/lib/python2.7/site-packages/linchpin/api/__init__.py", line 508, in run_playbook
18:05:25     rundb = self.setup_rundb()
18:05:25   File "/usr/lib/python2.7/site-packages/linchpin/api/__init__.py", line 410, in setup_rundb
18:05:25     os.mkdir(rundb_conn_dir)
18:05:25 OSError: [Errno 2] No such file or directory: '/home/jenkins/.config/linchpin'
```

Looks like the new rundb stuff has a bug when checking for configuration that may not exist.

**Comment by herlo** [comment]
I know exactly what is wrong. PR forthcoming. In the meantime, the workaround is just to create the directory structure.

**Comment by jaypoulz** [comment]
Duplicates #389

**Comment by herlo** [comment]
@jaypoulz are you using v1.2.1 which was just released yesterday? Would you be willing to update? I think this issue is fixed there.
