### ISSUE TITLE
Linchpin does not work with ansible 2.3.x 

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#563]
The following error occurs when we run linchpin up with dummy topology
```
Traceback (most recent call last):
  File "/home/srallaba/virtualenvs/test/bin/linchpin", line 11, in <module>
    sys.exit(runcli())
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/linchpin/shell/__init__.py", line 239, in up
    tx_id=tx_id)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/linchpin/cli/__init__.py", line 306, in lp_up
    tx_id=tx_id)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/linchpin/cli/__init__.py", line 421, in _execute_action
    run_id=run_id)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/linchpin/cli/__init__.py", line 554, in _execute
    tx_id=tx_id)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/linchpin/__init__.py", line 651, in do_action
    console=ansible_console)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/linchpin/__init__.py", line 811, in _invoke_playbooks
    console=console)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/linchpin/ansible_runner.py", line 170, in ansible_runner
    console=console)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/linchpin/ansible_runner.py", line 68, in ansible_runner_2x
    passwords)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 59, in __init__
    self._tqm = TaskQueueManager(inventory=inventory, variable_manager=variable_manager, loader=loader, options=options, passwords=self.passwords)
  File "/home/srallaba/virtualenvs/test/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 88, in __init__
    for path in options.module_path.split(os.pathsep):
AttributeError: 'list' object has no attribute 'split'
```

**Comment by samvarankashyap** [comment]
fixed by #564
