### ISSUE TITLE
Passing Openstack credentials only with environment variables

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#682]
When no authentication file provided and crenetials are set with environment variables, the following error returned when trying to deploy:
```
TASK [openstack : provision/teardown os_server resources with provided auth] ***
task path: /home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:2
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_h4N78C/ansible_module_os_server2.py", line 802, in <module>
    main()
  File "/tmp/ansible_h4N78C/ansible_module_os_server2.py", line 784, in main
    cloud = shade.openstack_cloud(**cloud_params)
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/shade/__init__.py", line 110, in openstack_cloud
    cloud_config = config.get_one_cloud(**kwargs)
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/openstack/config/loader.py", line 1042, in get_one
    auth_plugin = loader.load_from_options(**config['auth'])
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/keystoneauth1/loading/base.py", line 164, in load_from_options
    return self.create_plugin(**kwargs)
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/keystoneauth1/loading/base.py", line 125, in create_plugin
    return self.plugin_class(**kwargs)
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/keystoneauth1/identity/generic/password.py", line 32, in __init__
    super(Password, self).__init__(auth_url=auth_url, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'msg'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_h4N78C/ansible_module_os_server2.py\", line 802, in <module>\n    main()\n  File \"/tmp/ansible_h4N78C/ansible_module_os_server2.py\", line 784, in main\n    cloud = shade.openstack_cloud(**cloud_params)\n  File \"/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/shade/__init__.py\", line 110, in openstack_cloud\n    cloud_config = config.get_one_cloud(**kwargs)\n  File \"/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/openstack/config/loader.py\", line 1042, in get_one\n    auth_plugin = loader.load_from_options(**config['auth'])\n  File \"/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/keystoneauth1/loading/base.py\", line 164, in load_from_options\n    return self.create_plugin(**kwargs)\n  File \"/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/keystoneauth1/loading/base.py\", line 125, in create_plugin\n    return self.plugin_class(**kwargs)\n  File \"/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/keystoneauth1/identity/generic/password.py\", line 32, in __init__\n    super(Password, self).__init__(auth_url=auth_url, **kwargs)\nTypeError: __init__() got an unexpected keyword argument 'msg'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
        to retry, use: --limit @/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/linchpin/provision/openstack.retry
```

[Documentation] says "LinchPin honors the openstack environment variables such as $OS_USERNAME, $OS_PROJECT_NAME, etc."

[Documentation]: https://linchpin.readthedocs.io/en/v1.5.4/openstack.html

**Comment by herlo** [comment]
Hi @abraverm,

Can you provide a few bits of detail so we can troubleshoot this better? I'd like the PinFile (complete with topology and/or layout sections. Also, would you mind providing the command you used when you ran into this error? 

Thanks!

**Comment by abraverm** [comment]
```
export OS_USERNAME="ci"
export OS_PASSWORD="secret_password"
export OS_AUTH_URL="https://ci-rhos.redhat.com:13000"
export OS_TENANT_NAME="test"
```
PinFile:
```
---
simple:
  topology:
    topology_name: simple
    resource_groups:
      - resource_group_name: os-server-new
        resource_group_type: openstack
        resource_definitions:
          - name: "cci-linchpin-docs-example"
            role: os_server
            flavor: m1.small
            image: Fedora-Cloud-Base-28-released-latest
            count: 1
            keypair: ci-ops-central
            fip_pool: 10.8.240.0
            networks:
              - QE-test
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
        ansible_ssh_private_key_file: ci-ops-central
      hosts:
        example-node:
          count: 1
          host_groups:
            - example
```
command (from virtualenv): `linchpin -vvvv up`

**Comment by abraverm** [comment]
looks like if you create empty credentials file, than the environment variables kick in, clouds.yml
```
---
clouds:
  cirhos:
    auth: {}
```
PinFile:
```
...
        credentials:
          filename: clouds.yml
          profile: cirhos
```
