### ISSUE TITLE
linchpin fetch with dest causes regression 

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#705]
```
(ex_hooks) [srallaba@laptopy linchpin]$ linchpin fetch --dest /tmp/workspace https://github.com/samvarankashyap/linchpin_dummy_ws_hooks.git
Traceback (most recent call last):
  File "/home/srallaba/.virtualenvs/ex_hooks/bin/linchpin", line 11, in <module>
    load_entry_point('linchpin', 'console_scripts', 'linchpin')()
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/workspace/lp_ws/ex_hooks/linchpin/linchpin/shell/__init__.py", line 361, in fetch
    dest_ws=dest_ws, nocache=nocache)
  File "/home/srallaba/workspace/lp_ws/ex_hooks/linchpin/linchpin/cli/__init__.py", line 762, in lp_fetch
    uroot = hashlib.new(hash_string)
  File "/usr/lib64/python2.7/hashlib.py", line 130, in __hash_new
    return __get_builtin_constructor(name)(string)
  File "/usr/lib64/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256:https://github.com/samvarankashyap/linchpin_dummy_ws_hooks.git/tmp/workspace
```

**Comment by samvarankashyap** [comment]
I have updated the function
```
hashlib.new()
```
```
hashlib.sha224()
```
ref: https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/cli/__init__.py#L757 

it works fine however , it creates a random named folder at the destination which might not be needed .
```
(ex_hooks) [srallaba@laptopy linchpin]$ linchpin fetch --dest /tmp/workspace https://github.com/samvarankashyap/linchpin_dummy_ws_hooks.git
Created destination workspace: /tmp/workspace/fc30e49_
```

**Comment by samvarankashyap** [comment]
@herlo could you explain why the random numbered folder is generated due to fetch ? is it a feature ? 
For a end user just to copy from remote to destination without random numbered folder would be much better .

**Comment by herlo** [comment]
@samvarankashyap I already ran into this today and have a similar fix. Will have a PR up this afternoon. :smile:

As for the random numbered folder. In the olden days of fetch, everything was thrown into the current directory. The reason this is better is that now, unless you specify --dest (which will put workspaces relative to this location) or --workspace (this will drop the workspace(s) directly in the location specified), --dest provides a way for multiple workspaces to live in harmony. 

See [this](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/shell/__init__.py#L317) and [this](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/cli/__init__.py#L734) for more explanation. There are docs coming in the near future, but it's a bit of a long road atm.
