### ISSUE TITLE
Accidental deletes to topology folder causes regression 

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#706]
```
(ex_hooks) [srallaba@laptopy tmp]$ mkdir test
(ex_hooks) [srallaba@laptopy tmp]$ cd test/
(ex_hooks) [srallaba@laptopy test]$ linchpin init 
PinFile and file structure created at /tmp/test
(ex_hooks) [srallaba@laptopy test]$ ls
credentials  hooks  inventories  layouts  linchpin.conf  linchpin.log  localhost  PinFile  topologies
(ex_hooks) [srallaba@laptopy test]$ rm -rf topologies
(ex_hooks) [srallaba@laptopy test]$ linchpin -vvvv up
Traceback (most recent call last):
  File "/home/srallaba/.virtualenvs/ex_hooks/bin/linchpin", line 11, in <module>
    load_entry_point('linchpin', 'console_scripts', 'linchpin')()
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/srallaba/.virtualenvs/ex_hooks/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/workspace/lp_ws/ex_hooks/linchpin/linchpin/shell/__init__.py", line 255, in up
    inv_f=inventory_format)
  File "/home/srallaba/workspace/lp_ws/ex_hooks/linchpin/linchpin/cli/__init__.py", line 398, in lp_up
    tx_id=tx_id)
  File "/home/srallaba/workspace/lp_ws/ex_hooks/linchpin/linchpin/cli/__init__.py", line 561, in _execute_action
    provision_data = self._build(pf, pf_data=self.pf_data)
  File "/home/srallaba/workspace/lp_ws/ex_hooks/linchpin/linchpin/cli/__init__.py", line 649, in _build
    topology_path = self.find_include(pf[target]["topology"])
  File "/home/srallaba/workspace/lp_ws/ex_hooks/linchpin/linchpin/cli/__init__.py", line 609, in find_include
    files = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/test/topologies'
```

**Comment by samvarankashyap** [comment]
same with layouts folder too

**Comment by herlo** [comment]
@samvarankashyap I don't understand how this is a regression. Are you implying the error should not occur, or that it should be a pretty error? Please clarify how this is a regression as it would seem that I'd expect linchpin to fail if the topology doesn't exist. For the layout, I'm curious though, as it shouldn't matter at all.

**Comment by samvarankashyap** [comment]
@herlo Is linchpin not expected to create folders if not exists ? 
I thought that would happen .
Checking with allinone pinfiles . Will get you back .

**Comment by samvarankashyap** [comment]
does not occur when we use allinone pinfiles
sound resonable to have error when folders are not available
