### ISSUE TITLE
linchpin fails to provision in openstack with error "TypeError: up() got an unexpected keyword argument 'ignore_failed_hooks'"

### ISSUE THREAD

**Issue by mrniranjan** [CentOS-PaaS-SIG/linchpin#724]
```
Traceback (most recent call last):
  File "/opt/linchpin_dir/bin/linchpin", line 11, in <module>
    load_entry_point('linchpin==1.6.2', 'console_scripts', 'linchpin')()
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: up() got an unexpected keyword argument 'ignore_failed_hooks'

```
The above is the traceback i received when i ran 
```
linchpin -v -w /tmp/pnq --creds-path /tmp/pnq/credentials/ up"
```

Below is the topology file

```
topology_name: openstack_topo
resource_groups:
- resource_group_name: master
  resource_group_type: openstack
  resource_definitions:
  - name: 4284.testrelm.test
    type: os_server
    flavor: m1.small
    image: Fedora-Cloud-Base-26-compose-latest
    keypair: mniranja_linchpin
    count: 1
    networks:
    - idm-jenkins
    fip_pool: 10.8.240.0
  credentials:
    filename: clouds.yaml
    profile: devstack
```

 example-layout.yml 
```
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    master:
      count: 1
      host_groups:
      - master
      - sut
```

PinFile:
```
---
example_target:
  topology: example-topology.yml
  layout: example-layout.yml
```

**Comment by mrniranjan** [comment]
linchpin.conf
```
[DEFAULT]
pkg = linchpin
[lp]
rundb_conn = ~/.config/linchpin/rundb-::mac::.json
use_rundb_for_actions = True
distill_data = True
distill_on_error = False
[evars]
enable_uhash = True
generate_resources = False
[logger]
file = ~/.config/linchpin/linchpin.log
```

**Comment by samvarankashyap** [comment]
@mrniranjan : Could you please try upgrading your click package in the running environment and try it again ?
```
pip install click --upgrade
```
let me know if it still exists. 
Further could you post the output of the click version you are currently running ? 
```
pip show click
```

**Comment by samvarankashyap** [comment]
@mrniranjan : Am unable to replicate the error in my environment 
could you provide us the output of 
```
pip freeze
```

**Comment by samvarankashyap** [comment]
@mrniranjan @herlo : 
I have tested linchpin with multiple versions of click package . 
The above error is persistent in all the versions of click < 7.0 
I am creating PR to update minimum requirements to >=7.0
Thanks for reporting the error.

**Comment by mrniranjan** [comment]
@samvarankashyap  sorry for delay, i will reproduce the error again, don't have the environment  .
