### ISSUE TITLE
Openstack: Networking: Add support for os_recordset ansible module

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#822]
Add support for os_recordset ansible module in linchpin topologies
As a part of #786 
ref: https://docs.ansible.com/ansible/2.6/modules/os_recordset_module.html#os-recordset-module

**Comment by samvarankashyap** [comment]
Dependent on #823 
```
The full traceback is:
Traceback (most recent call last):
  File "/home/srallaba/.ansible/tmp/ansible-tmp-1544723069.89-235493270375918/AnsiballZ_os_zone.py", line 113, in <module>
    _ansiballz_main()
  File "/home/srallaba/.ansible/tmp/ansible-tmp-1544723069.89-235493270375918/AnsiballZ_os_zone.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/srallaba/.ansible/tmp/ansible-tmp-1544723069.89-235493270375918/AnsiballZ_os_zone.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_os_zone_payload_13qdiN/__main__.py", line 214, in <module>
  File "/tmp/ansible_os_zone_payload_13qdiN/__main__.py", line 162, in main
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py", line 8909, in get_zone
    return _utils._get_entity(self, 'zone', name_or_id, filters)
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/_utils.py", line 204, in _get_entity
    entities = search(name_or_id, filters, **kwargs)
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py", line 8912, in search_zones
    zones = self.list_zones()
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py", line 8891, in list_zones
    data = self._dns_client.get(
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py", line 568, in _dns_client
    'dns', min_version=2, max_version='2.latest')
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py", line 482, in _get_versioned_client
    endpoint_override=self.config.get_endpoint(service_type))
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 310, in get_api_major_version
    return self.session.get_api_major_version(auth or self.auth, **kwargs)
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/keystoneauth1/session.py", line 1146, in get_api_major_version
    return auth.get_api_major_version(self, **kwargs)
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 500, in get_api_major_version
    data = get_endpoint_data(discover_versions=discover_versions)
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 279, in get_endpoint_data
    service_name=service_name)
  File "/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/keystoneauth1/access/service_catalog.py", line 462, in endpoint_data_for
    raise exceptions.EndpointNotFound(msg)
keystoneauth1.exceptions.catalog.EndpointNotFound: public endpoint for dns service not found

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/srallaba/.ansible/tmp/ansible-tmp-1544723069.89-235493270375918/AnsiballZ_os_zone.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/srallaba/.ansible/tmp/ansible-tmp-1544723069.89-235493270375918/AnsiballZ_os_zone.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/srallaba/.ansible/tmp/ansible-tmp-1544723069.89-235493270375918/AnsiballZ_os_zone.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_os_zone_payload_13qdiN/__main__.py\", line 214, in <module>\n  File \"/tmp/ansible_os_zone_payload_13qdiN/__main__.py\", line 162, in main\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py\", line 8909, in get_zone\n    return _utils._get_entity(self, 'zone', name_or_id, filters)\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/_utils.py\", line 204, in _get_entity\n    entities = search(name_or_id, filters, **kwargs)\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py\", line 8912, in search_zones\n    zones = self.list_zones()\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py\", line 8891, in list_zones\n    data = self._dns_client.get(\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py\", line 568, in _dns_client\n    'dns', min_version=2, max_version='2.latest')\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py\", line 482, in _get_versioned_client\n    endpoint_override=self.config.get_endpoint(service_type))\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/keystoneauth1/adapter.py\", line 310, in get_api_major_version\n    return self.session.get_api_major_version(auth or self.auth, **kwargs)\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/keystoneauth1/session.py\", line 1146, in get_api_major_version\n    return auth.get_api_major_version(self, **kwargs)\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/keystoneauth1/identity/base.py\", line 500, in get_api_major_version\n    data = get_endpoint_data(discover_versions=discover_versions)\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/keystoneauth1/identity/base.py\", line 279, in get_endpoint_data\n    service_name=service_name)\n  File \"/home/srallaba/.virtualenvs/os_network/lib/python2.7/site-packages/keystoneauth1/access/service_catalog.py\", line 462, in endpoint_data_for\n    raise exceptions.EndpointNotFound(msg)\nkeystoneauth1.exceptions.catalog.EndpointNotFound: public endpoint for dns service not found\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```
Blocked on os_zone.
