### ISSUE TITLE
Openshift metadata name is not same as container name

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#876]
Pinfile:
```
---
simple:
  topology:
    topology_name: simple
    resource_groups:
      - resource_group_name: simple
        resource_group_type: openshift
        resource_definitions:
          - name: openshift
            role: openshift_inline
            namespace: cci-linchpin-docs
            definition:
              apiVersion: v1
              kind: Pod
              metadata:
                name: test1
                namespace: cci-linchpin-docs # Project name
                labels:
                  name: test1-pod
              spec:
                containers:
                  - image: bitnami/nginx
                    name: test2
                    ports:
                      - containerPort: 8080
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
      hosts:
        example-node:
          count: 1
          host_groups:
            - example
```

Error:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 539, in _execute
    self._task.post_validate(templar=templar)
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/ansible/playbook/task.py", line 267, in post_validate
    super(Task, self).post_validate(templar)
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/ansible/playbook/base.py", line 364, in post_validate
    value = templar.template(getattr(self, name))
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/ansible/template/__init__.py", line 540, in template
    disable_lookups=disable_lookups,
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/ansible/template/__init__.py", line 495, in template
    disable_lookups=disable_lookups,
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/ansible/template/__init__.py", line 743, in do_template
    res = j2_concat(rf)
  File "<template>", line 14, in root
  File "/home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/linchpin/provision/filter_plugins/get_pod_status.py", line 20, in get_pod_status
    if pod_stats[name]["status"] != "Running":
KeyError: u'test2'

fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```
Resources output:
```json
{
   "metadata":{
      "annotations":{
         "kubernetes.io/limit-ranger":"LimitRanger plugin set: cpu, memory request for container test2; cpu, memory limit for container test2",
         "openshift.io/scc":"restricted"
      },
      "creationTimestamp":"2018-12-24T13:45:12Z",
      "labels":{
         "name":"test1-pod"
      },
      "name":"test1",
      "namespace":"cci-linchpin-docs",
      "resourceVersion":"242748767",
      "selfLink":"/api/v1/namespaces/cci-linchpin-docs/pods/test1",
      "uid":"22b014b3-0782-11e9-adcd-fa163e4a655d"
   },
   "spec":{
      "containers":[
         {
            "image":"bitnami/nginx",
            "imagePullPolicy":"Always",
            "name":"test2",
            "ports":[
               {
                  "containerPort":8080,
                  "protocol":"TCP"
               }
            ],
            "resources":{
               "limits":{
                  "cpu":"500m",
                  "memory":"1000Mi"
               },
               "requests":{
                  "cpu":"300m",
                  "memory":"400Mi"
               }
            },
            "securityContext":{
               "capabilities":{
                  "drop":[
                     "KILL",
                     "MKNOD",
                     "SETGID",
                     "SETUID"
                  ]
               },
               "runAsUser":1002990000
            },
            "terminationMessagePath":"/dev/termination-log",
            "terminationMessagePolicy":"File",
            "volumeMounts":[
               {
                  "mountPath":"/var/run/secrets/kubernetes.io/serviceaccount",
                  "name":"default-token-gbjrh",
                  "readOnly":true
               }
            ]
         }
      ],
      "dnsPolicy":"ClusterFirst",
      "imagePullSecrets":[
         {
            "name":"default-dockercfg-2n896"
         }
      ],
      "nodeName":"cpt-0006.paas.prod.upshift.rdu2.redhat.com",
      "nodeSelector":{
         "region":"compute"
      },
      "restartPolicy":"Always",
      "schedulerName":"default-scheduler",
      "securityContext":{
         "fsGroup":1002990000,
         "seLinuxOptions":{
            "level":"s0:c55,c10"
         }
      },
      "serviceAccount":"default",
      "serviceAccountName":"default",
      "terminationGracePeriodSeconds":30,
      "tolerations":[
         {
            "effect":"NoSchedule",
            "key":"node.kubernetes.io/memory-pressure",
            "operator":"Exists"
         }
      ],
      "volumes":[
         {
            "name":"default-token-gbjrh",
            "secret":{
               "defaultMode":420,
               "secretName":"default-token-gbjrh"
            }
         }
      ]
   },
   "status":{
      "conditions":[
         {
            "lastProbeTime":null,
            "lastTransitionTime":"2018-12-24T13:45:12Z",
            "status":"True",
            "type":"Initialized"
         },
         {
            "lastProbeTime":null,
            "lastTransitionTime":"2018-12-24T13:45:23Z",
            "status":"True",
            "type":"Ready"
         },
         {
            "lastProbeTime":null,
            "lastTransitionTime":"2018-12-24T13:45:12Z",
            "status":"True",
            "type":"PodScheduled"
         }
      ],
      "containerStatuses":[
         {
            "containerID":"docker://b478148e9460141ea811f7ecda74846179ea7d25e723d50cf01788abb2463e23",
            "image":"docker.io/bitnami/nginx:latest",
            "imageID":"docker-pullable://docker.io/bitnami/nginx@sha256:7e5ccf043e08dd5f1d254fdd353103158be8fabc4a2967012d18b2f3841daed2",
            "lastState":{

            },
            "name":"test2",
            "ready":true,
            "restartCount":0,
            "state":{
               "running":{
                  "startedAt":"2018-12-24T13:45:21Z"
               }
            }
         }
      ],
      "hostIP":"10.0.18.69",
      "phase":"Running",
      "podIP":"172.54.251.203",
      "qosClass":"Burstable",
      "startTime":"2018-12-24T13:45:12Z"
   }
}
```

**Comment by samvarankashyap** [comment]
I see there is a problem with the pod name while checking for its status. I believe the problem occurs while fetching the data. We will try to fix this issue soon.
