### ISSUE TITLE
Libvirt destroy fails when _async = True

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#944]
```
TASK [libvirt : undefine node] **********************************************************************************************************************************************************
task path: /home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/linchpin/provision/roles/libvirt/tasks/teardown_libvirt_node.yml:32
skipping: [localhost] => (item=[{'count': 1, 'name': u'master', 'networks': [{'name': u'default'}], 'ssh_key': u'id_rsa', 'uri': u'qemu:///system', 'vcpus': 2, 'role': u'libvirt_node', 'memory': 8196, 'arch': u'x86_64', 'image_src': u'http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1608.qcow2.xz'}, 0])  => {"changed": false, "instance": [{"arch": "x86_64", "count": 1, "image_src": "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1608.qcow2.xz", "memory": 8196, "name": "master", "networks": [{"name": "default"}], "role": "libvirt_node", "ssh_key": "id_rsa", "uri": "qemu:///system", "vcpus": 2}, 0], "skip_reason": "Conditional result was False"}
Traceback (most recent call last):
  File "/home/ryan/.virtualenvs/linchpin-2/bin/linchpin", line 10, in <module>
    sys.exit(runcli())
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/linchpin/shell/__init__.py", line 360, in destroy
    tx_id=tx_id)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/linchpin/cli/__init__.py", line 509, in lp_destroy
    tx_id=tx_id)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/linchpin/cli/__init__.py", line 576, in _execute_action
    run_id=run_id)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/linchpin/cli/__init__.py", line 751, in _execute
    tx_id=tx_id)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/linchpin/__init__.py", line 615, in do_action
    console=ansible_console)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/linchpin/__init__.py", line 877, in _invoke_playbooks
    console=console)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/linchpin/__init__.py", line 837, in _find_n_run_pb
    console=console)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/linchpin/ansible_runner.py", line 191, in ansible_runner
    return_code = pbex.run()
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 156, in run
    result = self._tqm.run(play=play)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 291, in run
    play_return = strategy.run(iterator, play_context)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 282, in run
    task_vars = self._variable_manager.get_vars(play=iterator._play, host=host, task=task)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/ansible/vars/manager.py", line 432, in get_vars
    all_vars['ansible_delegated_vars'], all_vars['_ansible_loop_cache'] = self._get_delegated_vars(play, task, all_vars)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/ansible/vars/manager.py", line 506, in _get_delegated_vars
    loader=self._loader, fail_on_undefined=True, convert_bare=False)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/ansible/utils/listify.py", line 34, in listify_lookup_plugin_terms
    terms = templar.template(terms.strip(), convert_bare=convert_bare, fail_on_undefined=fail_on_undefined)
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/ansible/template/__init__.py", line 495, in template
    disable_lookups=disable_lookups,
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/ansible/template/__init__.py", line 743, in do_template
    res = j2_concat(rf)
  File "<template>", line 12, in root
  File "/home/ryan/.virtualenvs/linchpin-2/lib/python2.7/site-packages/linchpin/provision/filter_plugins/get_libvirt_files.py", line 9, in get_libvirt_files
    stdout = result['stdout']

```

**Comment by samvarankashyap** [comment]
@14rcole Though it gave an error ! did it destroy the machine ??
